export const routinesEn = {
  sleep: {
    title: '4 Month Old Sleep Schedule: A Flexible Day',
    description: 'Build a flexible four-month sleep routine with an example timeline, clear sleep-log totals, missing-data guidance and safe-sleep sources.',
    intro: 'A useful four-month sleep schedule starts with your baby’s recent days, feeding needs and signs of tiredness. A clock-time example can help you read a pattern, but it cannot prescribe your baby’s next nap. Use the illustrated log below to understand a day, then decide what to discuss with your care team.',
    sections: [
      ['How much sleep does the daily total include?', 'The AASM recommends 12–16 hours per 24 hours, including naps, for infants aged 4–12 months. This age-group guidance does not set an exact bedtime or nap count for an individual baby. {sleepSource}', 'Add completed sleep periods, not the time between going to bed and getting up. Separate time asleep from recorded waking, and keep periods you did not record marked as unknown. A total is useful only when you understand what went into it.'],
      ['Read yesterday before arranging today', 'Pick a consistent 24-hour window, such as 07:00 to 07:00 the next morning. Check the baby profile, start and end times, and any entry that crosses midnight. Correct an accidentally running timer before using the total.', 'Look for practical questions: Were the shortest naps on a busy afternoon? Is an apparent long night actually a timer left running? Does a blank period mean sleep was missed from the log? These questions are more useful than rating a day as good or bad.'],
      ['Explore an example sleep log', 'This fictional day contains three daytime sleep entries and three overnight entries, with waking between them. It teaches the arithmetic of a log; the number and timing of these sleeps are not recommendations. Feeds and other care are not plotted, and must not be delayed to fit the picture.', 'Switch to the incomplete log to see what happens when the afternoon was not recorded. The displayed sleep total falls even though we have no evidence that the baby actually slept less. The unrecorded interval is unknown, not awake time.'],
      ['Adjust the plan when the day changes', 'If a nap ends sooner than expected, record what happened and reassess the next part of the day using your baby’s cues. You do not have to keep an exhausted baby awake to reach a sample clock time. If the morning starts later, the example does not become a rule to rush every later activity.', 'Keep a simple, repeatable wind-down that fits your family. A different nap pattern is not, by itself, a reason to label the day a sleep regression or begin sleep training. Discuss persistent sleep concerns alongside feeding, growth, health and the effect on your family.'],
      ['Keep the sleep setting separate from the schedule', 'Place your baby on their back on a firm, flat sleep surface with a fitted sheet and no loose bedding or soft objects. Follow the linked AAP guidance for a suitable separate sleep space and for changes such as rolling. {safeSleep}', 'A tidy chart cannot show whether a sleeping environment is safe. For a baby born prematurely or receiving care for a medical condition, ask the care team how to interpret age and sleep advice for that baby.'],
      ['Record what you need; prepare a useful question', 'In BeMama, select the baby profile, record a sleep start and end, then review the entries in Reports. The app does not automatically detect sleep or promise next-nap prediction. Missing entries remain missing information. {tracking}', 'For a conversation with a professional, bring a few representative days and your question: “These are the periods we recorded; what context should we consider?” Note feeds and relevant changes separately. If your baby seems unwell or you are concerned about feeding or breathing, seek appropriate medical advice rather than adjusting a timetable.']
    ],
    takeaways: ['Count completed naps and overnight sleep within one defined day.', 'The AASM range applies to ages 4–12 months, not a prescribed schedule for every four-month-old.', 'An unrecorded period is unknown, not proof of wakefulness.', 'Do not delay a needed feed to match the example.', 'A sleep log supports observation; it does not predict, diagnose or assess sleep safety.'],
    faq: [
      ['Does a short nap mean the schedule is wrong?', 'One short entry cannot explain the whole day. Check that the record is complete and consider your baby’s cues and other care needs. Seek advice about a persistent concern rather than trying to hit the example times.'],
      ['Should I delay a feed to preserve a nap?', 'Do not use this illustration to delay feeding. Follow your baby’s feeding cues and any individualized feeding plan from your care team.'],
      ['Does the chart show how much sleep my baby needs?', 'No. It shows a fictional record and its arithmetic. The published age-group range is separate from the example, and your baby’s situation needs its own context.'],
      ['Can I use the incomplete total to compare two days?', 'Only with its limitation clearly stated. A lower recorded total can be caused by missing entries. Do not interpret it as a measured reduction in sleep.']
    ],
    evidence: { guidance: ['Use the age scope in the original AASM source. BeMama’s example is independently constructed and is not a clinical schedule from that organization.'], bemama: 'BeMama stores the care events you enter. Report totals summarize those entries and cannot reconstruct unrecorded sleep.', safety: 'A schedule must make room for feeding and care needs. Discuss concerns about your baby’s health with a qualified professional; this page cannot assess an individual baby.' }
  },
  feeding: {
    title: '6 Month Old Feeding Schedule: Milk and First Foods',
    description: 'Plan a flexible six-month feeding routine around milk, readiness and feeding cues, with a practical day guide and printable observation sheet.',
    intro: 'At around six months, a feeding routine can make space for first foods while milk feeds continue. Readiness, your baby’s cues and individual advice matter more than following a clock. Use the day-part example to organize opportunities, and the worksheet to remember what you observed.',
    sections: [
      ['Start with readiness and your baby’s usual feeds', 'The NHS and CDC describe introducing complementary foods around six months, with developmental readiness. Age alone is not the whole decision. If your baby was born prematurely or has an individual feeding plan, ask your care team how to begin. {feedingSource} {readiness}', 'Milk remains central while first foods are introduced. NHS guidance identifies breast milk or first infant formula as the main drink during the first year. Do not replace a milk feed simply because a sample timetable includes food.'],
      ['Check the setup before planning a food opportunity', 'Look for the readiness signs in the CDC guidance, including head and neck control, supported sitting and swallowing food rather than pushing it out. Arrange an upright, supported seat and stay with your baby during eating. Match preparation and texture to their abilities. {readiness}', 'Choose a calm opportunity when you have time to pay attention. This page does not impose a universal milk-first or solids-first rule: follow your local advice and your child’s feeding plan. The goal of this organizer is to make room for observation.'],
      ['An example day with flexible feeding opportunities', 'Read the rows as parts of a day, not a required number of feeds or meals. Milk feeds remain responsive throughout the day and, when needed, overnight. A first-food opportunity can move when your baby is tired or not interested.', 'No amounts or intake targets are assigned. The example does not require every family to offer the same foods, use the same milk, or follow the same order.'],
      ['Keep a feeding observation sheet', 'Record the time, whether it was a breast or bottle feed, and any food or texture offered. For bottles, record the amount and its original unit. For nursing, note timing or side only if useful; minutes at the breast must not be converted into milk volume.', 'Add what you noticed, such as turning away or showing interest, and any question for your care team. A blank amount is unknown, not zero. These notes are an observation record, not a nutrition score.'],
      ['When food is refused or a day looks different', 'If your baby turns away or closes their mouth, pause and respond to their cues rather than forcing the worksheet’s plan. You can record the observation without judging the day. Discuss ongoing refusal, intake worries or signs of illness with a health professional.', 'This guide does not set an allergy-introduction protocol or teach emergency choking care. Use authoritative local advice about food preparation, allergens and feeding safety, especially if your baby has a known allergy or another risk requiring individual guidance. {readiness}'],
      ['Use BeMama to remember events, not set intake targets', 'Choose the baby profile before recording. Use Nursing for a feed at the breast and Bottle for expressed milk or formula; keep the selected mL or oz unit with a bottle amount. Record solids separately and review the appropriate day in Reports. {tracking}', 'A missing entry can explain a gap in the report. The app cannot infer how much milk transferred during nursing or decide how much your baby needs. For first-food readiness and a broader overview, see {solids}.']
    ],
    takeaways: ['Start complementary foods around six months with readiness and individual advice.', 'First foods accompany milk; the example does not replace milk feeds.', 'Day parts are flexible opportunities, not mandatory meals or amounts.', 'Nursing duration and bottle volume describe different things.', 'Record cues and questions; use a professional for feeding concerns.'],
    faq: [
      ['Do solids replace milk feeds at six months?', 'Do not use this day-part example to replace milk. Early complementary foods accompany ongoing milk feeds. Follow the feeding advice appropriate to your baby.'],
      ['Must every day follow the same times?', 'No. Move the opportunity to suit your baby and your day, and respond to feeding cues. The example deliberately sets no clock times or required feed count.'],
      ['How many ounces or millilitres should I enter?', 'Record the bottle amount you actually observed and the unit you used, if you choose to record it. This worksheet does not calculate a target amount or convert nursing minutes into volume.'],
      ['Will BeMama tell me whether my baby has eaten enough?', 'The app organizes what you entered. It cannot assess intake sufficiency or diagnose a feeding problem. Bring concerns and relevant observations to your care team.']
    ],
    evidence: { guidance: ['The linked NHS and CDC pages provide the underlying information on first foods and readiness. National advice can differ in details; the example here is an organizer rather than a clinical feeding plan.'], bemama: 'Nursing time, bottle volume and solids are separate records. Reports reflect saved entries and do not measure milk transfer or nutritional adequacy.', safety: 'Use individual advice for premature birth, known allergy or feeding difficulties. Seek professional help for health or intake concerns; do not use a schedule to postpone care.' }
  }
};
