// Product instructions verified against the local 1.3.0 client; health text is education.
export default {
  product: {
    pumping: ['Open the child’s care screen and choose Pumping. Under amount style, choose Total or Left / right, then select mL or oz. Use Timer for a session in progress or Manual for one you have finished. Check the start time and amount before saving.', 'For example, a left entry of 40 mL and a right entry of 30 mL describe one 70 mL pumping session. These are sample records, not a supply target. Do not also log the same session as a separate total. Open its care-history entry to correct it. A later bottle feed is a different event.'],
    offline: ['Read the status on each care-history entry: Waiting to sync means the change is still local; Syncing means it is being sent; Synced confirms synchronization. Sync failed or Needs review calls for checking the entry rather than assuming it reached another device.', 'If a record is missing on another phone, first compare the account, child and event time. Reconnect the original phone and check its status. Keep the original local data until the issue is resolved; reinstalling is not a recovery step. If it still fails, send support the app version and error text, without private care notes.'],
    reports: ['In Reports, confirm the child’s name in the heading. With multiple children, use the child-switch icon. Choose Day, Week, List or Summary for the question you want to answer, and check the dates and activity selection. Standard summaries and extended 90/365-day comparisons have different access requirements.', 'For CSV, use the download icon in Reports. The current app first tries to synchronize, then exports the selected child’s latest 30 calendar days through today. The on-screen date or activity filter does not redefine that export window. Choose a file destination and inspect the dates in the saved CSV before sharing it.'],
    growth: ['Choose Growth in the child’s care screen. Set the measurement date and units, then enter only the measurements you have: weight, length/height or head circumference. Leave unknown measurements blank. Save the entry and check it in care history; correct the original entry if its date or unit is wrong.', 'The screenshot shows measurement entry, not a clinical growth assessment. Read the child, date and unit together before comparing points. Basic care logging, the app’s separate Premium tools and the free browser growth log are different workflows.'],
    caption: ['Care screen: selected child at the top, Pumping among the care actions, and saved entries in Care history. This existing tour image is in English; labels can vary by language and release.', 'Growth entry: check the start time, switch kg/cm or lb/in, and enter only available measurements. The existing tour screenshot shows the entry form.', 'Cycle calendar: compare recorded days with estimated dates. This existing English tour image illustrates the view; it is not a prediction of your personal fertility.'],
    csvSummary: 'Open Reports for the selected child. Day, Week, List and Summary organize the records differently. The current CSV download covers that child’s latest 30 calendar days through today; check the saved file’s dates rather than assuming it follows the visible report filters.',
    faq: [['Why is a CSV different from the report I am viewing?', 'The export currently uses the selected child and a rolling 30-day window. The screen can show a different range or activity selection. Compare the dates and entries before drawing conclusions.'], ['Can I fix a pumping entry without adding another session?', 'Yes. Open the saved entry in care history and edit it. Check the amount style, unit and time. Re-entering the same session as a new event can inflate recorded totals.']]
  },
  access: {
    intro: 'App access and access to an individual feature are separate. Within an accessible account, standard care records and reports differ from extended comparisons, AI and the Premium tools collection. The table separates those tasks; your account’s purchase screen confirms the offer available to you.',
    rows: [['Public website tools', 'Free without an app account. Saved browser records stay separate from the app.'], ['Daily guidance', 'Available after trial or subscription expiry.'], ['Basic care logging', 'Sign-in, app access and the correct child profile are required. Basic event recording has no separate Premium feature gate.'], ['Standard Reports and CSV', 'Available within app/profile access. CSV currently exports the latest 30 days; it does not follow all screen filters.'], ['90/365-day comparisons and AI insights', 'Require enabled AI access; these are separate from standard reports.'], ['Growth entry in care history', 'Part of care logging. Record measurements for the selected child.'], ['Separate Premium tools', 'Require Premium tools access; this includes the tools-area growth experience.'], ['Caregiver sharing', 'Requires authorized access to the child. Availability of invitation controls must be confirmed in your app version.'], ['AI consultation', 'Requires Premium plus enabled AI access. It provides educational support.'], ['Price, trial and platform access', 'Read the offer in your account. Web/mobile access and trial exclusions can differ; local store prices are authoritative.']],
    faq: [['Does logging a measurement unlock every growth tool?', 'No. The child’s care log and the separate Premium tools experience have different access paths. The public website growth log is also independent.'], ['Does a trial include every Premium function?', 'Not necessarily. Read the trial’s included features and renewal details in your account before accepting it.']]
  },
  cycleFaq: [['What should I record if I do not know my last period date?', 'Keep the uncertainty in your notes and use dates you actually know. Do not enter a guessed date as a confirmed observation. Discuss dating questions with your healthcare professional.'], ['Does one temperature rise confirm ovulation?', 'No. An isolated reading is not confirmation. Keep the measurement and its context, including illness or interrupted sleep, for a discussion with your clinician.']],
  sleep: {
    sections: [
      ['A sample observation, not a clock-based prescription', 'Use the example below to understand what a useful note contains. It describes one fragment of an invented day; it is not a recommended nap length or a complete day’s sleep total. Record your own start and end times, and leave unobserved periods unknown.'],
      ['When the day changes', 'If a nap ends earlier than expected, pause before moving every later event to a new timetable. Check feeding needs, comfort and sleepy cues. Write down what happened so a second caregiver can continue the same story. A short nap is a description, not a failure.', 'For evenings, choose a short sequence your household can repeat, such as a feed, a change and quiet time. Keep overnight care calm. Do not delay a needed feed to protect a planned bedtime. If your clinician has given waking or feeding instructions, those take priority.'],
      ['What to bring to a sleep conversation', 'Bring a few dated observations rather than only an average: sleep start/end, feeds, waking and any missing records. Add your main question, such as “Are these feeding interruptions expected for my baby?” A clinician can consider feeding, growth, illness and your family’s circumstances together.']
    ],
    table: {caption:'Illustrative observation sheet: one partial morning',headers:['Observed event','Useful note'],rows:[['09:10–09:45 · sleep','35 minutes recorded; woke and fed.'],['Next sleep · not recorded','Unknown, so excluded from the total.'],['Caregiver handover','Check the last event and any running timer.']]},
    faq: [['Must a three-month-old follow an exact wake window?', 'No single interval fits every baby or every day. Observe your child and use professional advice for feeding or health concerns rather than forcing an app timetable.'], ['Does night waking mean the routine is wrong?', 'Night waking still occurs at this age. A log can describe it, but cannot determine the cause or whether a feed should be removed.'], ['Can I compare today with another baby?', 'Use your own records to notice changes. Another family’s clock times do not establish what your baby needs. Ask for help if sleep or feeding is persistently difficult.']]
  },
  feeding: {
    sections: [
      ['A meal-planning example you can adapt', 'Use meal opportunities as anchors, with usual breast milk or infant formula feeds continuing around them. At this stage, babies build skills at different speeds. The table shows what to observe, without prescribing portions or requiring a finished plate.'],
      ['Read interest and fullness alongside the clock', 'Reaching toward food or opening the mouth can show interest. Turning away or closing the mouth can signal fullness. Give your baby time and allow them to stop. If you are worried about how little they eat, ask their healthcare professional rather than repeatedly pressing another spoonful.', 'Keep the baby seated upright and stay with them throughout eating. Food softness, shape and preparation matter with both spoon-feeding and finger foods. The linked choking-prevention guide covers hazards; learn age-appropriate first aid from a qualified provider.'],
      ['Make changes easy to explain to another caregiver', 'Record the food, preparation and texture, not just “lunch.” Add what you observed and distinguish food offered from food eaten. Keep notes factual: “turned away after a few tastes” gives more context than “bad eater.” Tell the next caregiver about any concern and follow the care plan for a known allergy.']
    ],
    table:{caption:'Flexible meal opportunities, with milk feeds continuing',headers:['Part of the day','Planning prompt'],rows:[['Morning','Choose an alert, supervised opportunity; note texture and interest.'],['Midday','Offer familiar foods and skill practice suited to your baby.'],['Evening','Keep the setting calm; record what was offered and the response.']]},
    faq:[['Do I have to choose only purées or only baby-led weaning?', 'You can use spoon-fed and self-fed foods together. Choose preparation your baby can manage and respond to their cues. Discuss feeding difficulties or special needs with a professional.'], ['Should a seven- or eight-month-old finish every meal?', 'No. Offered food and eaten food are different. Follow hunger and fullness cues and seek advice if intake or growth worries you.'], ['Can the food log tell me whether a reaction is an allergy?', 'No. Record what happened and obtain medical advice. Breathing difficulty or a severe reaction needs emergency help, not another log entry.']]
  },
  weeks: [
    ['5 weeks pregnant: dates and first steps', 'A late period may be your first clue, while tiredness or breast tenderness may also occur. Symptoms vary. Around this stage the embryo is approximately 2 mm long in the NHS illustration; a size comparison describes development, not the health of an individual pregnancy.', 'Start a short appointment note: the first day of the last period if known, test dates, current medicines and the questions you want answered. Contact your local maternity service to arrange care. If your dates are uncertain, say so; keep your record separate from the estimated due date.'],
    ['6 weeks pregnant: symptoms and useful notes', 'Nausea can happen throughout the day. Limb buds are developing; the NHS gives an approximate embryo length of 6 mm. Symptoms or their absence do not replace clinical assessment.', 'If nausea is affecting you, note when it occurs, whether you can keep fluids down and what you want to ask about support. Contact your clinician if food or fluids will not stay down. Do not wait for the next weekly article when you need care, and do not stop prescribed medicine without advice.'],
    ['8 weeks pregnant: prepare for the first appointments', 'The NHS describes an embryo around 16 mm long at this stage. Energy, mood and symptoms can change. A fruit-size image is an educational comparison, not a measurement of your pregnancy.', 'Prepare your medical and pregnancy history, medicine list and practical questions. Ask what appointments and tests are offered locally, how results are explained and whom to contact between visits. Tell the team about ongoing low mood or anxiety so support can begin early.']
  ],
  weeksFaq:[['Why did my estimated pregnancy week change?', 'The starting dates may have been uncertain, or your care team may have revised the dating after assessment. Keep the original observations and the clinician-confirmed date clearly distinguished.'], ['Can symptom strength tell me whether development is normal?', 'Symptoms alone cannot establish this. Contact your maternity service about worrying changes. Severe pain, fainting or heavy bleeding needs urgent assessment.']],
  postpartum: {
    sections:[
      ['First days: make recovery instructions usable', 'Before leaving care, clarify wound or perineal care, prescribed medicines, warning signs and the next contact. Put the instructions where you and your helper can find them. Choose who will handle meals, laundry, other children and transport, so asking for help does not become another task.', 'Keep a separate note for your own recovery. Record a concern in plain language with its time, then call the appropriate service when needed. A baby-care log should not hide the parent’s need for assessment.'],
      ['Weeks 1–2: review support, not a recovery score', 'Look at what makes the day harder: pain, feeding worries, interrupted rest or having no practical help. Ask about symptoms that are worsening or preventing everyday activities. After a caesarean, follow your team’s wound and activity instructions rather than a generic exercise timetable.', 'Agree one small handover routine: what help is needed today, what appointments are coming and who can take over while you rest. There is no required week when you should feel back to normal.'],
      ['Weeks 3–6 and beyond: keep the parent’s follow-up', 'Keep postpartum appointments even if most conversations have focused on the baby. Services differ by country; ask your team when your own review should happen. At the review, discuss pain, bleeding, bladder or bowel concerns, mood, feeding, contraception and return to activity as relevant.', 'Write the questions before the visit and note what follow-up was agreed. Persistent symptoms deserve attention after six weeks too. Recovery does not finish simply because an appointment or calendar milestone has passed.']
    ],
    faq:[['Do I need to wait for the routine check if something is wrong?', 'No. Seek urgent care for warning signs such as chest pain, breathing difficulty, heavy bleeding, fainting or thoughts of harming yourself or your baby. Tell the clinician you recently gave birth.'], ['Is recovery after a caesarean the same as after a vaginal birth?', 'Some needs overlap, but wound care, pain and activity advice can differ. Follow your own discharge plan and contact the team if instructions are unclear or symptoms worsen.']]
  }
};
