import { productRollout } from './product-rollout.mjs';
export const translations = productRollout('es', 'Guía del producto de {name}, fundador de BeMama.', {
  daily: 'Configurar el seguimiento del embarazo', tracking: 'Registrar tomas, sueño y pañales', premium: 'Funciones gratuitas y Premium', start: 'Primeros pasos con BeMama', tools: 'Herramientas gratuitas para embarazo y crianza', privacy: 'Privacidad y exportación de datos', terms: 'Condiciones de suscripción', contact: 'Contactar con soporte', website: 'Sitio web de BeMama', app: 'Abrir la app de BeMama'
}, {
  'why-bemama': {
    title: 'BeMama: seguimiento del embarazo y del bebé',
    description: 'Conoce BeMama para seguir el embarazo y registrar tomas, sueño y pañales del bebé, con calculadoras y listas gratuitas en la web.',
    intro: 'BeMama reúne orientación durante el embarazo y registros del cuidado del bebé. Consulta tu recorrido diario, guarda eventos en el perfil de tu hijo o utiliza las calculadoras y listas de esta web. Empieza por lo que te ayude hoy.',
    sections: [
      ['Durante el embarazo: seguir cada semana', 'Configura el recorrido con la fecha que pide la app. El recorrido diario organiza los contenidos por etapa; las herramientas estiman semana, trimestre y fecha de parto. Para la atención clínica, sigue la datación de tu equipo de salud.', 'Consulta la configuración: {daily}'],
      ['Después del nacimiento: reunir los cuidados diarios', 'El perfil del bebé tiene registros separados de lactancia, biberones, sueño, alimentos y pañales. Selecciona el perfil, anota la hora y los detalles, y revisa los informes del día o la semana.', 'Las notas ayudan a recordar y preparar preguntas. No miden la leche que recibe al pecho, determinan cuánto necesita ni diagnostican problemas de sueño o crecimiento.'],
      ['Orientación, comunidad y ayuda de la IA', 'Los espacios de preguntas y comunidad permiten compartir experiencias. Consulta las cuestiones médicas con un profesional. Las explicaciones asistidas por IA pueden equivocarse y no son un diagnóstico ni un servicio de urgencias.', 'Antes de elegir una suscripción: {premium}'],
      ['Herramientas gratuitas en la web', 'Estima la ovulación o la fecha de parto, prepara la bolsa del hospital o una lista para el recién nacido, o registra su crecimiento. Las listas permiten añadir tareas y notas, ver el progreso, imprimir y descargar copias. No necesitas una cuenta de la app.', 'Consulta cada herramienta y sus instrucciones: {tools}'],
      ['Elegir por dónde empezar', 'Abre {app} o usa los enlaces de Android e iOS de la web. Los registros de las herramientas web son independientes y no aparecen automáticamente en tu cuenta de la app.', 'Configuración, primeros registros y copias: {start}']
    ],
    takeaways: ['El recorrido diario se organiza según la etapa elegida.', 'Cada perfil del bebé reúne tomas, sueño y pañales en informes.', 'Las herramientas web son gratuitas y no piden cuenta de la app.', 'Los registros web y los de la cuenta son independientes.', 'Utiliza las notas y estimaciones para preparar conversaciones con tu equipo de salud.'],
    faq: [['¿BeMama es una app de embarazo o de seguimiento del bebé?', 'Sirve para ambas etapas: orientación durante el embarazo y perfiles con tomas, sueño y pañales después del nacimiento. La web también ofrece guías y herramientas.'], ['¿Puedo probar una herramienta sin cuenta?', 'Sí. Elige una calculadora o lista en {tools}. Las funciones de la cuenta de la app tienen un inicio de sesión aparte.'], ['¿Sustituye la atención médica?', 'No. Ofrece información, estimaciones y registros, sin diagnóstico, prescripción ni atención de urgencias.']]
  },
  tools: {
    title: 'Seguimiento del bebé: lactancia, sueño y pañales',
    description: 'Aprende a registrar lactancia, biberones, sueño y pañales en BeMama, consultar informes y usar las herramientas gratuitas de la web.',
    intro: 'Anota qué ocurrió, cuándo y a qué bebé corresponde. Combina el registro de lactancia y biberones con el de sueño y pañales, y revisa los informes. Estas funciones de la app son distintas de las herramientas gratuitas de la web.',
    sections: [
      ['Selecciona el perfil correcto', 'Inicia sesión y configura la etapa del bebé con su fecha de nacimiento. Comprueba el perfil seleccionado antes de registrar un cuidado; las acciones disponibles cambian entre las etapas de bebé y niño.', 'Anota los detalles útiles, revisa hora y perfil y guarda. Corrige los errores con los controles de edición de la entrada.'],
      ['Lactancia: registrar una toma al pecho', 'Elige lactancia y el pecho de inicio. Usa el temporizador durante una toma o la entrada manual cuando ya haya terminado. Revisa las horas de inicio y fin; detén el temporizador al terminar.', 'La duración y el lado son datos del registro. No miden el volumen de leche transferido ni permiten saber si la toma fue suficiente.'],
      ['Biberón: tipo de leche y cantidad', 'Elige biberón, indica la hora, selecciona leche materna o fórmula y la unidad mL u oz. Anota la cantidad y guarda; comprueba la unidad al revisar o cambiar de dispositivo.', 'El registro recuerda las cantidades introducidas. No recomienda un objetivo de ingesta ni explica cómo preparar la fórmula: sigue las instrucciones del producto y de tu profesional.'],
      ['Sueño: guardar un período de descanso', 'Elige sueño e indica inicio y fin con los controles disponibles. Si hay un temporizador en marcha, detenlo cuando el bebé despierte. Revisa las entradas completas para ver siestas y sueño nocturno.', 'El registro depende de lo que introduzcas. No detecta automáticamente el sueño, predice la próxima siesta ni evalúa la seguridad al dormir.'],
      ['Pañales: anotar el cambio', 'Elige pañal, selecciona el tipo y guarda la hora. Encontrarás estos eventos junto a las tomas del mismo perfil.', 'Consulta las entradas para recordar el día o preparar una cita. Contar pañales por sí solo no confirma hidratación ni descarta enfermedad.'],
      ['Revisar informes y descargar registros', 'Las vistas Día, Semana, Lista y Resumen organizan los datos del bebé seleccionado. El informe permite descargar un CSV de los registros disponibles: revisa perfil y fechas antes de exportar.', 'Un período vacío puede indicar que faltan registros. Los totales describen las entradas guardadas, sin diagnosticar ni evaluar el crecimiento o el éxito de una rutina.', 'El análisis con IA y algunas funciones avanzadas tienen acceso independiente: {premium}'],
      ['Calculadoras, listas y crecimiento en la web', 'En {tools} encontrarás estimaciones de ovulación y parto, calendario de citas y síntomas, listas de preparación, nombres favoritos y registro de crecimiento, sin cuenta de la app.', 'Añade tareas y notas, filtra, marca lo terminado o lo que no necesitas y descarga o imprime una copia. El registro de crecimiento dibuja tus medidas y ofrece referencias de peso para la edad de la OMS en las edades admitidas; no calcula un percentil individual.', 'Los datos guardados permanecen en este dispositivo, sin sincronización automática con la app. Borrar el almacenamiento del navegador puede eliminarlos; conserva copias descargadas.', 'Para los datos de tu cuenta: {privacy}']
    ],
    takeaways: ['Comprueba el perfil antes de registrar una toma, sueño o pañal.', 'La lactancia registra tiempo y lado; el biberón, leche, cantidad y unidad.', 'Los informes ofrecen vistas Día, Semana, Lista y Resumen y descarga CSV.', 'La falta de registros es información ausente.', 'La web y la app mantienen registros separados: guarda copias.'],
    faq: [['¿Puedo registrar tomas y pañales juntos?', 'Sí. Guarda cada toma al pecho, biberón y cambio con su hora en el perfil del bebé y consulta sus informes.'], ['¿Y si combino pecho y biberón?', 'Usa lactancia para el pecho y biberón para leche extraída o fórmula. Los minutos al pecho y el volumen del biberón no son medidas equivalentes de ingesta.'], ['¿Predice la próxima siesta?', 'El seguimiento guarda períodos de sueño y muestra los registros. No promete predicciones ni un plan de sueño personalizado.'], ['¿El registro de crecimiento web aparece en la app?', 'No. Los datos web se guardan en el dispositivo. Usa sus copias de seguridad e introduce por separado en la app la información que necesites.'], ['¿Todo el seguimiento es gratuito?', 'El acceso depende de la cuenta y plataforma. El recorrido diario y las herramientas públicas no exigen Premium activo; consulta el acceso a funciones avanzadas e IA en la app.']]
  },
  premium: {
    title: 'BeMama gratis y Premium: acceso a las funciones',
    description: 'Conoce el recorrido diario gratuito, las herramientas web y el acceso a funciones Premium de BeMama antes de elegir una suscripción.',
    intro: 'Elige las funciones según tu tarea: leer el recorrido, registrar cuidados, preparar una lista o consultar una explicación con IA. La app muestra el acceso de tu cuenta y plataforma; no todas sus funciones son necesariamente gratuitas.',
    sections: [
      ['Recorrido diario sin Premium activo', 'En la app actual, el recorrido diario sigue disponible tras finalizar una prueba o suscripción. Puedes continuar con los contenidos de tu etapa, incluido el embarazo, sin comprar Premium.', 'Configúralo aquí: {daily}'],
      ['Herramientas públicas sin cuenta', 'Las calculadoras, listas y demás herramientas de {tools} son gratuitas. No requieren inicio de sesión ni compra de Premium.', 'Sus registros están separados de la cuenta de la app. Cuando haya una opción de copia, descárgala para conservar los datos fuera del navegador.'],
      ['Funciones con requisitos adicionales', 'Las herramientas avanzadas, algunas funciones comunitarias y la IA tienen controles de acceso propios. Por ejemplo, ciertas herramientas de crecimiento con registros guardados y el análisis de informes con IA dependen de las capacidades de tu cuenta.', 'Abre la función deseada y lee su pantalla de acceso o mejora. Comprueba funciones incluidas, precio, renovación y límites de prueba. Premium no promete atención prioritaria, consulta clínica ni un resultado concreto.'],
      ['Antes de contratar o cambiar la suscripción', 'Revisa {terms} y los detalles de la tienda o pantalla de compra. Gestiona la suscripción desde la plataforma donde la contrataste.', 'Si faltan funciones o necesitas ayuda: {contact}. No envíes los datos completos de tu tarjeta.']
    ],
    takeaways: ['El recorrido diario no requiere Premium activo.', 'Las herramientas web son gratuitas y no piden cuenta.', 'Las funciones avanzadas y la IA pueden necesitar acceso adicional.', 'Consulta las funciones y facturación en la pantalla de compra actual.', 'Los registros web y de la cuenta son independientes.'],
    faq: [['¿Pierdo el recorrido al terminar la prueba?', 'En la app actual, el recorrido diario sigue disponible sin Premium activo. El acceso a otras funciones puede cambiar.'], ['¿Necesito Premium para las calculadoras web?', 'No. Las calculadoras y listas públicas funcionan sin cuenta de la app ni Premium.'], ['¿Dónde veo precio y funciones?', 'En las pantallas de funciones y suscripción de tu cuenta y plataforma. Lee las condiciones antes de comprar.'], ['¿Premium incluye atención médica?', 'No. Las herramientas y la IA sirven para organización e información general, no diagnóstico, tratamiento o urgencias.']]
  },
  'getting-started': {
    title: 'Primeros pasos con BeMama: embarazo y bebé',
    description: 'Configura tu recorrido y perfil del bebé en BeMama, guarda tu primer registro o prueba las herramientas gratuitas de la web sin cuenta.',
    intro: 'Empieza por algo útil: seguir tu semana de embarazo, anotar un biberón o preparar la bolsa del hospital. La app y las herramientas web tienen procesos distintos de configuración y guardado.',
    sections: [
      ['1. Elige la app o una herramienta web', 'Para el recorrido diario y el seguimiento del bebé, abre {app} o descarga BeMama con los enlaces Android e iOS. Elige el idioma y crea una cuenta o inicia sesión.', 'Para una calculadora o lista sin cuenta, abre {tools} y lee las instrucciones antes de introducir datos.'],
      ['2. Configura la etapa correcta', 'Elige planificación, embarazo, bebé o niño y completa los datos solicitados. Revisa las etiquetas: la última menstruación y el nacimiento del bebé son fechas con usos diferentes.', 'Actualiza el recorrido al cambiar de etapa. Comprueba el perfil del bebé antes de añadir eventos para asignarlos al niño correcto.', 'Para embarazo y estimaciones de progreso: {daily}'],
      ['3. Registra un evento y compruébalo', 'En el perfil del bebé, elige lactancia, biberón, sueño o pañal. Introduce hora y detalles, comprueba y guarda. Detén un temporizador cuando termine el evento.', 'Abre los informes y verifica bebé y día. Edita los errores en lugar de crear entradas duplicadas.', 'Instrucciones de cada registro: {tracking}'],
      ['4. Guarda copias del trabajo en la web', 'En una lista, marca tareas terminadas o innecesarias, añade las tuyas y notas y usa los filtros. El progreso refleja las tareas que cuentan para completarla.', 'Utiliza las opciones de guardado y copia que ofrezca la herramienta. Descarga o imprime lo que quieras conservar. Los datos permanecen en este dispositivo y no se sincronizan con la app; borrar el almacenamiento del navegador puede eliminarlos.'],
      ['5. Revisa acceso y datos', 'El recorrido diario y las herramientas públicas no necesitan Premium activo. Consulta otros requisitos en {premium}.', 'Antes de guardar datos sensibles, lee {privacy}. Solicita la exportación mientras tu cuenta siga activa si necesitas una copia. Para ayuda de acceso o cuenta: {contact}.']
    ],
    takeaways: ['Usa una cuenta para el recorrido y seguimiento del bebé.', 'Prueba las herramientas web sin crear cuenta.', 'Comprueba etapa, perfil, fecha y unidades antes de guardar.', 'Revisa tu primer evento en los informes y corrige errores.', 'Conserva copias y distingue los registros web de los de la app.'],
    faq: [['¿Puedo usar BeMama en la web?', 'Sí: {app}. Los contenidos y herramientas públicas están en {website}. La sesión de la app y el guardado web son independientes.'], ['¿Qué registro primero?', 'Un evento útil de recordar, como una toma o período de sueño. Comprueba perfil y hora, guarda y revisa el informe.'], ['¿Por qué el informe está vacío?', 'Comprueba bebé, fechas y que la entrada se haya guardado. Un informe vacío no significa que no hubo cuidados. Consulta con soporte si faltan registros esperados.'], ['¿Tengo que registrarlo todo?', 'No. Elige lo que te ayude y sigue las indicaciones de seguimiento de tu equipo de salud. La app organiza información; no es un requisito para cuidar bien.']]
  }
});
