import { productRollout } from './product-rollout.mjs';
export const translations = productRollout('tr', 'BeMama’nın kurucusu {name} tarafından hazırlanan ürün rehberi.', {
  daily: 'Gebelik takibini kurma', tracking: 'Beslenme, uyku ve bez kayıtları', premium: 'Ücretsiz ve Premium özellikler', start: 'BeMama’ya başlarken', tools: 'Ücretsiz gebelik ve bakım araçları', privacy: 'Gizlilik ve veri dışa aktarma', terms: 'Abonelik koşulları', contact: 'Destek ile iletişim', website: 'BeMama web sitesi', app: 'BeMama uygulamasını aç'
}, {
  'why-bemama': {
    title: 'BeMama: gebelik ve bebek takibi',
    description: 'BeMama ile gebeliğinizi takip edin, bebeğinizin beslenme, uyku ve bez kayıtlarını tutun; ücretsiz web hesaplayıcılarını ve listeleri keşfedin.',
    intro: 'BeMama, gebelik bilgilerini ve bebek bakım kayıtlarını bir araya getirir. Günlük Yolculuk içeriğini okuyun, bebeğinizin profilinde bakım olaylarını kaydedin veya bu sitedeki ücretsiz hesaplayıcı ve listeleri kullanın. Bugün işinize yarayan görevle başlayın.',
    sections: [
      ['Gebelikte: haftanızı takip edin', 'Uygulamanın istediği tarihle gebelik yolculuğunu kurun. Günlük Yolculuk içeriği aşamanıza göre düzenler; araçlar hafta, trimester ve doğum tarihi tahminleri sunar. Sağlık bakımında ekibinizin belirlediği gebelik tarihini esas alın. Kurulum: {daily}'],
      ['Doğumdan sonra: günlük bakımı bir arada tutun', 'Bebek profilinde emzirme, biberon, uyku, ek gıda ve bez için ayrı kayıtlar bulunur. Profili seçip saati ve ayrıntıları kaydedin; gün veya hafta raporuna bakın.', 'Kayıtlar hatırlamaya ve soru hazırlamaya yardımcı olur. Emzirirken alınan süt miktarını ölçmez, bebeğin ihtiyacını belirlemez ve uyku ya da büyüme sorunlarına tanı koymaz.'],
      ['Bilgi, topluluk ve yapay zekâ desteği', 'Soru-cevap ve topluluk alanları deneyim paylaşmayı sağlar. Tıbbi soruları yetkin bir sağlık uzmanına yöneltin. Yapay zekâ açıklamaları yanlış olabilir; tanı veya acil yardım hizmeti değildir. Abonelik öncesinde okuyun: {premium}'],
      ['Web sitesindeki ücretsiz araçlar', 'Yumurtlama ve doğum tarihi tahminlerini hesaplayın, hastane çantası veya yenidoğan listesi hazırlayın, büyüme kaydı tutun. Listelere görev ve not ekleyebilir, ilerlemeyi izleyebilir, yazdırabilir ve yedek indirebilirsiniz. Uygulama hesabı gerekmez. Araçlar ve kullanım bilgileri: {tools}'],
      ['Başlangıç noktanızı seçin', '{app} bağlantısını veya sitedeki Android ve iOS indirme bağlantılarını kullanın. Web araçlarının kayıtları ayrıdır; uygulama hesabında kendiliğinden görünmez. Kurulum, kayıt ve yedekleme adımları: {start}']
    ],
    takeaways: ['Günlük Yolculuk seçtiğiniz aşamaya göre içerik sunar.', 'Bebek profili beslenme, uyku ve bez kayıtlarını raporlarda toplar.', 'Ücretsiz web araçları uygulama hesabı istemez.', 'Web aracı ve uygulama hesabı kayıtları ayrıdır.', 'Not ve tahminleri sağlık ekibinizle görüşmeye hazırlanmak için kullanın.'],
    faq: [['BeMama hamilelik uygulaması mı, bebek takip uygulaması mı?', 'İkisini de destekler: gebelikte aşamaya göre Günlük Yolculuk, doğumdan sonra beslenme, uyku ve bez kayıtları. Web sitesinde ayrıca rehberler ve ücretsiz araçlar bulunur.'], ['Hesapsız araç deneyebilir miyim?', 'Evet. {tools} içinden bir hesaplayıcı veya liste seçin. Uygulama hesabının ayrı bir giriş süreci vardır.'], ['Tıbbi bakımın yerini alır mı?', 'Hayır. Bilgi, tahmin ve kayıt sunar; tanı, reçete veya acil bakım sağlamaz.']]
  },
  tools: {
    title: 'Bebek takibi: emzirme, uyku ve bez kayıtları',
    description: 'BeMama’da emzirme, biberon, uyku ve bez kaydı tutmayı, raporları incelemeyi ve ücretsiz web araçlarını kullanmayı adım adım öğrenin.',
    intro: 'Ne olduğunu, saatini ve hangi bebeğe ait olduğunu kaydedin. Emzirme ve biberon kayıtlarını uyku ve bez kayıtlarıyla birlikte raporlarda inceleyin. Uygulamadaki bu iş akışları, sitedeki ücretsiz araçlardan ayrıdır.',
    sections: [
      ['Doğru bebek profiliyle başlayın', 'Giriş yapın ve doğum tarihiyle bebek yolculuğunu kurun. Bakım kaydı eklemeden önce seçili profili kontrol edin; bebek ve çocuk aşamalarındaki işlemler farklıdır. Ayrıntıları ve saati kontrol edip kaydedin. Hataları kaydın düzenleme kontrolleriyle düzeltin.'],
      ['Emzirme takibi: bir emzirmeyi kaydedin', 'Emzirmeyi ve başlangıç memesini seçin. Şu anki emzirme için zamanlayıcı, bitmiş bir emzirme için elle giriş kullanın. Elle girişte başlangıç ve bitiş saatini kontrol edin; zamanlayıcıyı emzirme bitince durdurun.', 'Süre ve taraf kaydedilir. Süre, bebeğin aldığı süt miktarını ölçmez ve yeterli beslenip beslenmediğini belirlemez.'],
      ['Biberon: süt türü ve miktarı', 'Biberonu seçip saati girin; anne sütü veya mama ile mL ya da oz birimini seçin. Miktarı kaydedin. Kayıtları incelerken veya cihaz değiştirirken birimi kontrol edin.', 'Takipçi yalnızca girdiğiniz miktarları hatırlatır. Hedef tüketim önermez veya mama hazırlama talimatı vermez; ürün talimatlarını ve sağlık uzmanınızın önerilerini izleyin.'],
      ['Uyku: bir uyku dönemini kaydedin', 'Uyku bölümündeki başlangıç ve bitiş kontrollerini kullanın. Çalışan zamanlayıcıyı bebeğiniz uyanınca bitirin; tamamlanmış kayıtlarda gündüz ve gece uykusunu inceleyin.', 'Kayıt sizin girişlerinize bağlıdır. Uykuyu otomatik algılamaz, sonraki uykuyu tahmin etmez ve uyku ortamının güvenliğini değerlendirmez.'],
      ['Bez: değişimi not edin', 'Bez kaydını ve türünü seçip saati kaydedin. Aynı bebek profilindeki emzirme ve biberon kayıtlarıyla birlikte görüntüleyin. Bunlar bir günü hatırlamaya veya görüşmeye hazırlanmaya yardımcıdır; bez sayısı tek başına sıvı alımının yeterli olduğunu doğrulamaz ve hastalığı dışlamaz.'],
      ['Raporları inceleyin ve dışa aktarın', 'Seçili bebeğin Gün, Hafta, Liste ve Özet görünümlerini açın. CSV indirme, mevcut kayıtların kopyasını saklamanızı sağlar; önce profil ve tarih aralığını kontrol edin.', 'Boş dönemler kayıt girilmediği anlamına gelebilir. Toplamlar kaydedilen olayları gösterir; tanı, büyüme değerlendirmesi veya rutinin işe yaradığının kanıtı değildir. Yapay zekâ analizi ve bazı gelişmiş özelliklerin erişimini kontrol edin: {premium}'],
      ['Web araçları: hesaplayıcılar, listeler ve büyüme kaydı', '{tools} hesap istemez. Yumurtlama ve doğum tarihi tahmini, randevu ve belirti takvimi, hazırlık listeleri, bebek adı listesi ve büyüme kaydı içerir.', 'Listelerde görev ve not ekleyin, filtreleyin, tamamlanan veya gereksiz görevleri işaretleyin, yazdırın ve yedek indirin. Büyüme kaydı ölçümlerinizi çizer ve desteklenen yaşlar için DSÖ yaşa göre ağırlık referansı gösterir; bireysel persentil hesaplamaz.', 'Kaydettiğiniz web verileri bu cihazda kalır, uygulamayla otomatik eşitlenmez. Tarayıcı verilerini silmek kayıtları kaldırabilir; gereken yedekleri indirin. Hesap verilerinin saklanması: {privacy}']
    ],
    takeaways: ['Her kayıttan önce bebek profilini kontrol edin.', 'Emzirme süre ve tarafı; biberon süt türü, miktar ve birimi kaydeder.', 'Gün, Hafta, Liste ve Özet raporları ile CSV indirme bulunur.', 'Eksik kayıt, bakım yapılmadığının kanıtı değildir.', 'Web ve uygulama kayıtları ayrıdır; yedekleri saklayın.'],
    faq: [['Beslenme ve bezleri birlikte takip edebilir miyim?', 'Evet. Emzirme, biberon ve bez değişimlerini saatleriyle bebek profiline kaydedin; ardından o bebeğin raporlarını inceleyin.'], ['Hem emziriyor hem biberon veriyorsam?', 'Memede beslenme için emzirme, sağılmış süt veya mama için biberon kaydını kullanın. Emzirme dakikaları ile biberon hacmi eşdeğer alım ölçümleri değildir.'], ['Bir sonraki uykuyu tahmin eder mi?', 'Uyku dönemlerini kaydeder ve girilen verileri gösterir. Sonraki uyku tahmini veya kişisel uyku planı vaat etmez.'], ['Web büyüme kaydım uygulamada görünür mü?', 'Hayır. Web kayıtları cihazda tutulur. Yedek kontrollerini kullanın ve uygulamada istediğiniz bilgileri ayrıca girin.'], ['Bütün özellikler ücretsiz mi?', 'Erişim hesaba ve platforma göre değişebilir. Günlük Yolculuk ve herkese açık web araçları aktif Premium istemez; gelişmiş araçlar ve yapay zekâ erişimini uygulamada kontrol edin.']]
  },
  premium: {
    title: 'BeMama ücretsiz ve Premium özellikleri',
    description: 'BeMama’nın ücretsiz Günlük Yolculuk içeriğini, web araçlarını ve Premium özelliklere erişimi abonelik seçmeden önce karşılaştırın.',
    intro: 'Özelliği yapmak istediğiniz işe göre seçin: yolculuğu okumak, bakım kaydı tutmak, liste hazırlamak veya yapay zekâ açıklamasını incelemek. Uygulama hesabınız ve platformunuz için erişimi gösterir; bütün özellikler ücretsiz olmayabilir.',
    sections: [
      ['Aktif Premium olmadan Günlük Yolculuk', 'Mevcut uygulamada deneme veya abonelik sona erince Günlük Yolculuk kullanılabilir kalır. Gebelik dahil aşamanızın içeriklerini okumaya devam etmek için Premium satın almanız gerekmez. Kurulum: {daily}'],
      ['Hesapsız herkese açık araçlar', '{tools} içindeki hesaplayıcı ve listeler ücretsizdir; giriş veya Premium satın alma istemez. Kayıtları uygulama hesabından ayrıdır. Yedekleme sunuluyorsa tarayıcı dışında saklamak için bir kopya indirin.'],
      ['Ek erişim gerektiren özellikler', 'Gelişmiş araçlar, bazı topluluk işlevleri ve yapay zekâ ayrı erişim kontrollerine sahiptir. Kayıtlı büyüme araçları ve raporların yapay zekâ analizi gibi özellikler hesabın yetkilerine bağlı olabilir.', 'İstediğiniz özelliğin erişim veya yükseltme ekranını okuyun. Dahil olan özellikleri, fiyatı, yenileme dönemini ve deneme sınırlarını kontrol edin. Premium öncelikli bakım, klinik görüşme veya belirli sonuç vaat etmez.'],
      ['Abonelik almadan veya değiştirmeden önce', '{terms} ile mağaza ya da satın alma ekranındaki ayrıntıları okuyun. Aboneliği satın aldığınız platformdan yönetin. Eksik erişim veya hesap yardımı için {contact} kullanın; tam kart bilgilerinizi göndermeyin.']
    ],
    takeaways: ['Günlük Yolculuk aktif Premium gerektirmez.', 'Herkese açık web araçları ücretsizdir ve hesap istemez.', 'Gelişmiş araçlar ve yapay zekâ ek erişim gerektirebilir.', 'Güncel satın alma ekranındaki özellik ve ödeme koşullarını kontrol edin.', 'Web ve uygulama hesabı kayıtları ayrıdır.'],
    faq: [['Deneme bitince Günlük Yolculuk kapanır mı?', 'Mevcut uygulamada aktif Premium olmadan kullanılabilir kalır. Diğer yeteneklere erişim değişebilir.'], ['Web hesaplayıcıları için Premium gerekir mi?', 'Hayır. Herkese açık hesaplayıcı ve listeler hesap veya Premium aboneliği istemez.'], ['Güncel fiyat ve özellikler nerede?', 'Hesabınız ve platformunuz için uygulamanın özellik ve abonelik ekranlarında. Satın almadan önce koşulları da okuyun.'], ['Premium tıbbi bakım içerir mi?', 'Hayır. Araçlar ve yapay zekâ açıklamaları düzenleme ve genel eğitim içindir; tanı, tedavi veya acil bakım sağlamaz.']]
  },
  'getting-started': {
    title: 'BeMama’ya başlarken: gebelik ve bebek bakımı',
    description: 'BeMama’da yolculuğunuzu ve bebek profilini kurun, ilk bakım kaydını kontrol edin veya web araçlarını hesap oluşturmadan deneyin.',
    intro: 'Gebelik haftanıza bakmak, biberon kaydı tutmak veya hastane çantası hazırlamak gibi tek bir yararlı görevle başlayın. Uygulama ve web araçlarının kurulum ve kayıt süreçleri farklıdır.',
    sections: [
      ['1. Uygulamayı veya web aracını seçin', 'Günlük Yolculuk ve bebek takibi için {app} bağlantısını veya Android ve iOS indirme bağlantılarını kullanın. Dil seçip hesap oluşturun ya da giriş yapın. Hesapsız hesaplayıcı veya liste için {tools} açın ve bilgi girmeden önce kullanım açıklamasını okuyun.'],
      ['2. Doğru yolculuğu kurun', 'Planlama, gebelik, bebek veya çocuk aşamasını seçin ve istenen bilgileri tamamlayın. Son adet tarihi ile çocuğun doğum tarihi farklı amaçlar taşır; alan etiketlerini kontrol edin.', 'Aşamanız değişince yolculuğu güncelleyin. Kayıttan önce doğru bebek profilini seçin. Gebelik kurulumu ve ilerleme tahminleri: {daily}'],
      ['3. Bir olay kaydedip kontrol edin', 'Bebek profilinde emzirme, biberon, uyku veya bez seçin. Saat ve ayrıntıları kontrol edip kaydedin; olay bittiğinde zamanlayıcıyı durdurun.', 'Raporlarda doğru bebek ve günü kontrol edin. İkinci kopya eklemek yerine kaydı düzenleyin. Ayrıntılı adımlar: {tracking}'],
      ['4. Web aracındaki çalışmanızı yedekleyin', 'Listelerde tamamlanan veya gereksiz işleri işaretleyin, kendi görev ve notlarınızı ekleyin ve filtreleri kullanın. İlerleme, tamamlanmaya dahil edilen görevleri sayar.', 'Sunulan kaydetme ve yedekleme kontrollerini kullanın; saklayacağınız kopyayı indirin veya yazdırın. Veriler bu cihazda kalır ve uygulamayla otomatik eşitlenmez. Tarayıcı verilerini silmek kayıtları kaldırabilir.'],
      ['5. Erişim ve veri tercihlerini kontrol edin', 'Günlük Yolculuk ve herkese açık araçlar aktif Premium istemez. Diğer koşullar: {premium}. Hassas kayıtlar tutmadan önce {privacy} bilgilerini okuyun; kopya gerekiyorsa hesabınız aktifken dışa aktarma isteyin. Yardım: {contact}.']
    ],
    takeaways: ['Günlük Yolculuk ve bebek takibi için uygulama hesabı kullanın.', 'Web araçlarını hesap açmadan deneyin.', 'Kaydetmeden önce aşama, profil, tarih ve birimleri kontrol edin.', 'İlk kaydı raporlarda inceleyip hataları düzeltin.', 'Yedek saklayın; web ve uygulama verilerinin ayrı olduğunu unutmayın.'],
    faq: [['BeMama’yı web üzerinde kullanabilir miyim?', 'Evet: {app}. Rehberler ve herkese açık araçlar {website} üzerindedir. Uygulamaya giriş ve web aracında kayıt ayrı işlemlerdir.'], ['İlk neyi kaydetmeliyim?', 'Hatırlamak istediğiniz bir emzirme, biberon veya uyku dönemiyle başlayın. Profili ve saati kontrol edin, kaydedip rapora bakın.'], ['Raporum neden boş?', 'Seçili bebeği, tarih aralığını ve kaydın kaydedilip kaydedilmediğini kontrol edin. Boş rapor bakım yapılmadığı anlamına gelmez. Beklediğiniz kayıtlar yoksa destekle iletişim kurun.'], ['Her şeyi kaydetmem gerekir mi?', 'Hayır. Size yararlı kayıtları seçin ve sağlık ekibinizin takip önerilerine uyun. Uygulama bir düzenleyicidir; iyi ebeveynliğin şartı değildir.']]
  }
});
