import { productRollout } from './product-rollout.mjs';
export const translations = productRollout('fr', 'Guide produit par {name}, fondateur de BeMama.', {
  daily: 'Configurer le suivi de grossesse', tracking: 'Suivi de bébé : repas, sommeil et couches', premium: 'Accès gratuit et Premium', start: 'Premiers pas avec BeMama', tools: 'Outils gratuits pour la grossesse et bébé', privacy: 'Confidentialité et export des données', terms: 'Conditions d’abonnement', contact: 'Contacter l’assistance', website: 'Site BeMama', app: 'Ouvrir l’application BeMama'
}, {
  'why-bemama': {
    title: 'BeMama : suivi de grossesse et de bébé',
    description: 'Découvrez BeMama pour suivre la grossesse et noter les repas, le sommeil et les couches de bébé, avec des outils gratuits sur le site.',
    intro: 'BeMama réunit des repères pour la grossesse et un carnet de suivi de bébé. Consultez votre parcours quotidien, enregistrez les soins dans le profil de votre enfant ou utilisez les calculateurs et listes du site. Commencez par ce qui vous aide aujourd’hui.',
    sections: [
      ['Pendant la grossesse : suivre les semaines', 'Configurez votre parcours avec la date demandée dans l’application. Le parcours quotidien organise les contenus selon votre étape ; les outils estiment la semaine, le trimestre et la date d’accouchement. Pour vos soins, suivez la datation retenue par votre équipe médicale.', 'Les étapes de configuration : {daily}'],
      ['Après la naissance : garder une trace des soins', 'Le suivi de bébé comporte des entrées distinctes pour l’allaitement, les biberons, le sommeil, les aliments et les couches. Sélectionnez le bon profil, notez l’heure et les détails utiles, puis consultez les rapports du jour ou de la semaine.', 'Ces notes aident à se souvenir et à préparer des questions. Elles ne mesurent pas le lait reçu au sein, ne déterminent pas les besoins de bébé et ne diagnostiquent pas un problème de sommeil ou de croissance.'],
      ['Conseils, communauté et aide de l’IA', 'Les espaces de questions et de communauté permettent d’échanger des expériences. Les questions médicales relèvent d’un professionnel qualifié. Les explications assistées par IA peuvent être erronées ; elles ne constituent ni un diagnostic ni un service d’urgence.', 'Avant de choisir un abonnement : {premium}'],
      ['Des outils gratuits sur le site', 'Estimez l’ovulation ou la date d’accouchement, préparez une liste pour la maternité ou bébé, ou consignez sa croissance. Les listes permettent d’ajouter des tâches et des notes, de suivre la progression, d’imprimer et de télécharger une sauvegarde. Aucun compte d’application n’est nécessaire.', 'Consultez les fonctions et instructions de chaque outil : {tools}'],
      ['Choisir votre point de départ', 'Ouvrez {app} ou utilisez les liens Android et iOS du site. Les données des outils du site restent séparées : elles n’apparaissent pas automatiquement dans votre compte d’application.', 'Configuration, premières notes et sauvegardes : {start}']
    ],
    takeaways: ['Le parcours quotidien suit l’étape que vous avez sélectionnée.', 'Un profil bébé rassemble les repas, le sommeil et les couches dans des rapports.', 'Les outils du site fonctionnent gratuitement sans compte d’application.', 'Les données du site et celles de l’application restent séparées.', 'Les notes et estimations peuvent préparer vos échanges avec l’équipe de soins.'],
    faq: [
      ['BeMama suit-elle la grossesse ou le bébé ?', 'Les deux : le parcours quotidien accompagne la grossesse et les profils bébé rassemblent les repas, le sommeil et les couches. Le site propose aussi des guides et outils gratuits.'],
      ['Puis-je essayer un outil sans compte ?', 'Oui. Choisissez un calculateur ou une liste dans {tools}. Les fonctions du compte d’application ont leur propre connexion.'],
      ['BeMama remplace-t-elle les soins médicaux ?', 'Non. Elle propose des informations, des estimations et des notes, sans diagnostic, prescription ni prise en charge des urgences.']
    ]
  },
  tools: {
    title: 'Suivi de bébé : allaitement, sommeil et couches',
    description: 'Apprenez à noter allaitement, biberons, sommeil et couches dans BeMama, à consulter les rapports et à utiliser les outils gratuits du site.',
    intro: 'Le suivi de bébé permet de noter un événement, son heure et l’enfant concerné. Combinez le suivi de l’allaitement et des biberons avec les notes de sommeil et de couches, puis consultez les rapports. Ces fonctions de l’application sont distinctes des outils gratuits du site.',
    sections: [
      ['Sélectionner le bon profil bébé', 'Connectez-vous, configurez le parcours bébé avec sa date de naissance, puis vérifiez le profil sélectionné dans le suivi. Les actions proposées diffèrent entre les étapes bébé et enfant.', 'Renseignez les détails utiles, vérifiez l’heure et le profil, puis enregistrez. Utilisez la modification de l’entrée pour corriger une erreur.'],
      ['Suivi de l’allaitement : enregistrer une tétée', 'Choisissez l’allaitement et le sein de départ. Utilisez le minuteur pour une tétée en cours ou la saisie manuelle pour une tétée terminée. Vérifiez le début et la fin d’une saisie manuelle ; arrêtez le minuteur à la fin de la tétée.', 'La durée et le côté sont des observations. Ils ne mesurent pas le volume de lait reçu et ne permettent pas de juger si bébé a suffisamment bu.'],
      ['Biberons : noter le lait et la quantité', 'Choisissez le biberon, saisissez l’heure, puis sélectionnez lait maternel ou préparation pour nourrissons. Choisissez mL ou oz et notez la quantité. Vérifiez l’unité lorsque vous consultez les données ou changez d’appareil.', 'Le carnet conserve les quantités saisies. Il ne fixe pas un objectif de consommation et ne remplace pas les instructions de préparation du lait ni les conseils de votre professionnel.'],
      ['Suivi du sommeil : enregistrer une période', 'Choisissez le sommeil et indiquez le début et la fin avec les commandes proposées. Si un minuteur tourne, arrêtez-le au réveil. Les entrées terminées montrent les périodes de sieste et de sommeil nocturne.', 'Le suivi dépend de vos saisies. Il ne détecte pas automatiquement le sommeil, ne prédit pas la prochaine sieste et ne vérifie pas la sécurité du couchage.'],
      ['Couches : noter chaque change utile', 'Choisissez l’entrée de couche, indiquez le type et enregistrez l’heure. Vous retrouvez ces notes avec celles des tétées et biberons dans le même profil.', 'Consultez-les pour vous souvenir d’une journée ou préparer un rendez-vous. Le nombre de couches ne suffit pas à confirmer une bonne hydratation ou à exclure une maladie.'],
      ['Lire les rapports et exporter vos notes', 'Les vues Jour, Semaine, Liste et Résumé organisent les données du bébé sélectionné. Le téléchargement CSV conserve une copie des enregistrements disponibles : vérifiez le profil et la période avant l’export.', 'Une période vide peut simplement ne pas avoir été renseignée. Les totaux décrivent les entrées enregistrées, sans diagnostic ni évaluation de la croissance ou de la qualité d’une routine.', 'L’analyse assistée par IA et certaines fonctions avancées ont des conditions d’accès distinctes : {premium}'],
      ['Outils du site : calculateurs, listes et courbe de croissance', 'Les outils de {tools} ne demandent pas de compte. Ils comprennent les estimations d’ovulation et d’accouchement, le calendrier de rendez-vous et symptômes, les listes de préparation, les prénoms favoris et le carnet de croissance.', 'Ajoutez des tâches et notes, filtrez les listes, marquez les éléments terminés ou inutiles, puis imprimez ou sauvegardez. Le carnet trace vos mesures et affiche une référence OMS du poids selon l’âge pour les âges pris en charge ; il ne calcule pas un percentile individuel.', 'Les données sauvegardées restent sur cet appareil et ne se synchronisent pas automatiquement avec l’application. Effacer les données du navigateur peut les supprimer : téléchargez les sauvegardes à conserver.', 'Pour les données du compte et leur conservation : {privacy}']
    ],
    takeaways: ['Vérifiez le profil bébé avant chaque saisie.', 'Les tétées enregistrent durée et côté ; les biberons enregistrent type de lait, quantité et unité.', 'Les rapports proposent les vues Jour, Semaine, Liste et Résumé, ainsi qu’un export CSV.', 'Une absence de saisie est une donnée manquante.', 'Les outils du site sont séparés de l’application : conservez vos sauvegardes.'],
    faq: [
      ['Peut-on suivre les repas et les couches ensemble ?', 'Oui. Enregistrez chaque tétée, biberon ou change avec son heure dans le profil bébé, puis consultez ses rapports.'],
      ['Et si j’allaite et donne aussi des biberons ?', 'Utilisez l’allaitement pour les tétées au sein et le biberon pour le lait exprimé ou la préparation infantile. Durée de tétée et volume au biberon ne sont pas des mesures équivalentes.'],
      ['Le suivi prédit-il la prochaine sieste ?', 'Il conserve les périodes de sommeil et montre les données enregistrées. Il ne promet pas de prédiction de sieste ni de programme personnalisé.'],
      ['Mon carnet de croissance du site apparaît-il dans l’application ?', 'Non. Les données du site restent sur l’appareil. Utilisez la sauvegarde et saisissez séparément les informations souhaitées dans l’application.'],
      ['Toutes les fonctions de suivi sont-elles gratuites ?', 'L’accès dépend du compte et de la plateforme. Le parcours quotidien et les outils publics ne demandent pas d’abonnement Premium actif ; vérifiez les fonctions avancées et l’IA dans l’application.']
    ]
  },
  premium: {
    title: 'BeMama gratuit et Premium : accès aux fonctions',
    description: 'Comprenez l’accès au parcours quotidien gratuit, aux outils du site et aux fonctions Premium de BeMama avant de choisir un abonnement.',
    intro: 'Choisissez les fonctions utiles : lire votre parcours, noter les soins, préparer une liste ou consulter une explication assistée par IA. L’application affiche l’accès disponible pour votre compte et votre plateforme ; toutes ses fonctions ne sont pas nécessairement gratuites.',
    sections: [
      ['Le parcours quotidien sans abonnement Premium actif', 'Dans l’application actuelle, le parcours quotidien reste accessible après la fin d’un essai ou d’un abonnement. Vous pouvez continuer à lire les contenus de votre étape, dont ceux de grossesse, sans acheter Premium.', 'Pour le configurer : {daily}'],
      ['Les outils publics sans compte d’application', 'Les calculateurs, listes et autres outils de {tools} sont gratuits. Ils ne demandent ni connexion ni achat Premium.', 'Leurs données restent séparées du compte d’application. Lorsqu’une sauvegarde est proposée, téléchargez-en une copie pour la conserver hors du navigateur.'],
      ['Les fonctions avec des conditions d’accès supplémentaires', 'Des outils avancés, certaines fonctions communautaires et l’IA ont des accès distincts. Cela concerne notamment des outils de croissance enregistrés et l’analyse de rapports par IA, selon les droits de votre compte.', 'Ouvrez la fonction souhaitée et l’écran d’accès ou d’abonnement. Vérifiez les fonctions incluses, le prix, la période de renouvellement et les limites de l’essai. Premium ne promet ni soins prioritaires, ni consultation clinique, ni résultat particulier.'],
      ['Avant de souscrire ou de modifier un abonnement', 'Lisez {terms} et les informations affichées au moment de l’achat. Gérez l’abonnement sur la plateforme où vous l’avez souscrit.', 'Pour un problème d’accès ou de compte : {contact}. Ne transmettez pas les données complètes de votre carte bancaire.']
    ],
    takeaways: ['Le parcours quotidien ne demande pas de Premium actif.', 'Les outils publics sont gratuits et accessibles sans compte.', 'Les outils avancés et l’IA peuvent nécessiter un accès supplémentaire.', 'Vérifiez les fonctions et la facturation sur l’écran d’achat actuel.', 'Les données du site et du compte d’application restent séparées.'],
    faq: [
      ['Le parcours quotidien s’arrête-t-il à la fin de l’essai ?', 'Dans l’application actuelle, il reste accessible sans abonnement Premium actif. L’accès à d’autres fonctions peut changer.'],
      ['Faut-il Premium pour les calculateurs et listes du site ?', 'Non. Ces outils publics fonctionnent sans compte d’application ni abonnement Premium.'],
      ['Où voir le prix et les fonctions incluses ?', 'Consultez les écrans de fonction et d’abonnement de votre compte et plateforme, puis les conditions avant l’achat.'],
      ['Premium comprend-il des soins médicaux ?', 'Non. Les outils et explications assistées par IA servent à l’organisation et à l’information générale, pas au diagnostic, au traitement ou aux urgences.']
    ]
  },
  'getting-started': {
    title: 'Commencer avec BeMama : grossesse et suivi de bébé',
    description: 'Configurez votre parcours et le profil bébé dans BeMama, enregistrez un premier soin ou essayez les outils gratuits du site sans compte.',
    intro: 'Commencez par une tâche utile : consulter votre semaine de grossesse, noter un biberon ou préparer la valise de maternité. La configuration et la sauvegarde diffèrent entre l’application et les outils du site.',
    sections: [
      ['1. Choisir l’application ou un outil du site', 'Pour le parcours quotidien et le suivi de bébé, ouvrez {app} ou téléchargez BeMama avec les liens Android et iOS du site. Choisissez la langue, puis créez un compte ou connectez-vous.', 'Pour un calculateur ou une liste sans compte, ouvrez {tools}. Lisez les instructions avant de saisir des données.'],
      ['2. Configurer le bon parcours', 'Choisissez projet de grossesse, grossesse, bébé ou enfant et renseignez les informations demandées. Vérifiez les libellés : la date des dernières règles et la date de naissance de l’enfant ont des usages différents.', 'Actualisez le parcours quand votre étape change. Avant une saisie de soins, vérifiez le profil bébé pour attribuer les notes au bon enfant.', 'Pour le suivi de grossesse : {daily}'],
      ['3. Enregistrer puis vérifier un événement', 'Dans le profil bébé, choisissez une tétée, un biberon, du sommeil ou une couche. Renseignez l’heure et les détails, vérifiez puis enregistrez. Arrêtez tout minuteur lorsque l’événement se termine.', 'Ouvrez les rapports et vérifiez le bébé et le jour. Corrigez une entrée avec la modification plutôt que de créer un doublon.', 'Les étapes détaillées : {tracking}'],
      ['4. Sauvegarder le travail dans les outils du site', 'Dans une liste, marquez les tâches terminées ou inutiles, ajoutez les vôtres et filtrez l’affichage. La progression tient compte des tâches retenues pour la liste.', 'Utilisez les commandes de sauvegarde proposées et téléchargez ou imprimez une copie. Les données restent sur cet appareil, sans synchronisation automatique avec l’application ; effacer les données du navigateur peut les supprimer.'],
      ['5. Vérifier l’accès et les choix de données', 'Le parcours quotidien et les outils publics ne demandent pas de Premium actif. Pour les autres conditions d’accès : {premium}.', 'Avant de garder des notes sensibles, consultez {privacy}. Demandez l’export souhaité pendant que votre compte est actif. Pour obtenir de l’aide : {contact}.']
    ],
    takeaways: ['Le parcours quotidien et le suivi bébé utilisent un compte d’application.', 'Les outils publics peuvent être essayés sans compte.', 'Vérifiez étape, profil, date et unités avant d’enregistrer.', 'Contrôlez la première entrée dans les rapports et corrigez les erreurs.', 'Conservez vos sauvegardes et distinguez les données du site de celles de l’application.'],
    faq: [
      ['Puis-je utiliser BeMama sur le Web ?', 'Oui : {app}. Les guides et outils publics se trouvent sur {website}. La connexion à l’application et la sauvegarde du site sont distinctes.'],
      ['Que noter en premier ?', 'Un événement que vous souhaitez retenir, comme une tétée, un biberon ou une période de sommeil. Vérifiez profil et heure, enregistrez, puis consultez le rapport.'],
      ['Pourquoi mon rapport est-il vide ?', 'Vérifiez le bébé, la période et l’enregistrement de l’entrée. Un rapport vide ne signifie pas qu’aucun soin n’a eu lieu. Contactez l’assistance si des notes attendues manquent.'],
      ['Dois-je tout enregistrer ?', 'Non. Gardez les notes qui vous aident et suivez les consignes de suivi de votre équipe de soins. Utiliser l’application n’est pas une condition pour être un bon parent.']
    ]
  }
});
