import { productRollout } from './product-rollout.mjs';
export const translations = productRollout('pt', 'Guia do produto por {name}, fundador da BeMama.', {
  daily: 'Configurar o acompanhamento da gravidez', tracking: 'Registrar mamadas, sono e fraldas', premium: 'Recursos gratuitos e Premium', start: 'Primeiros passos na BeMama', tools: 'Ferramentas gratuitas para gravidez e cuidados', privacy: 'Privacidade e exportação de dados', terms: 'Termos de assinatura', contact: 'Falar com o suporte', website: 'Site da BeMama', app: 'Abrir o aplicativo BeMama'
}, {
  'why-bemama': {
    title: 'BeMama: acompanhamento da gravidez e do bebê',
    description: 'Conheça a BeMama para acompanhar a gravidez e registrar mamadas, sono e fraldas do bebê, com calculadoras e listas gratuitas no site.',
    intro: 'A BeMama reúne orientações para a gravidez e registros dos cuidados do bebê. Consulte a Jornada Diária, registre eventos no perfil da criança ou use as calculadoras e listas deste site. Comece pelo que ajuda hoje.',
    sections: [
      ['Na gravidez: acompanhar cada semana', 'Configure a jornada com a data solicitada no aplicativo. A Jornada Diária organiza conteúdos por fase; as ferramentas estimam semana, trimestre e data provável do parto. Para o pré-natal, siga a datação da sua equipe de saúde.', 'Veja a configuração: {daily}'],
      ['Depois do nascimento: reunir os cuidados', 'O perfil do bebê tem registros separados de amamentação, mamadeira, sono, alimentos e fraldas. Selecione o perfil, anote horário e detalhes e consulte os relatórios do dia ou da semana.', 'As anotações ajudam a lembrar e preparar perguntas. Elas não medem o leite recebido no peito, definem a necessidade do bebê ou diagnosticam problemas de sono e crescimento.'],
      ['Orientações, comunidade e apoio de IA', 'Os espaços de perguntas e comunidade permitem trocar experiências. Leve questões médicas a um profissional qualificado. Explicações com IA podem estar erradas e não são diagnóstico nem atendimento de emergência.', 'Antes de escolher uma assinatura: {premium}'],
      ['Ferramentas gratuitas no site', 'Estime a ovulação ou a data do parto, prepare a mala da maternidade e listas para o recém-nascido ou registre o crescimento. As listas permitem tarefas e notas próprias, acompanhamento do progresso, impressão e cópia para download. Não é preciso ter conta no aplicativo.', 'Veja as instruções de cada ferramenta: {tools}'],
      ['Escolher por onde começar', 'Abra {app} ou use os links de Android e iOS do site. As ferramentas públicas mantêm registros separados, que não aparecem automaticamente na conta do aplicativo.', 'Configuração, primeiros registros e cópias: {start}']
    ],
    takeaways: ['A Jornada Diária acompanha a fase selecionada.', 'O perfil do bebê reúne alimentação, sono e fraldas em relatórios.', 'As ferramentas do site são gratuitas e funcionam sem conta.', 'Os registros do site e do aplicativo ficam separados.', 'Use notas e estimativas para preparar conversas com a equipe de saúde.'],
    faq: [['A BeMama é um aplicativo de gravidez ou de acompanhamento do bebê?', 'Atende às duas fases: orientações por etapa na gravidez e perfis com alimentação, sono e fraldas depois do nascimento. O site também oferece guias e ferramentas.'], ['Posso testar uma ferramenta sem conta?', 'Sim. Escolha uma calculadora ou lista em {tools}. Os recursos da conta do aplicativo têm um acesso separado.'], ['A BeMama substitui atendimento médico?', 'Não. Oferece informação, estimativas e registros, sem diagnóstico, prescrição ou atendimento de emergência.']]
  },
  tools: {
    title: 'Registro do bebê: amamentação, sono e fraldas',
    description: 'Aprenda a registrar amamentação, mamadeiras, sono e fraldas na BeMama, consultar relatórios e usar as ferramentas gratuitas do site.',
    intro: 'Registre o que aconteceu, em que horário e com qual bebê. Combine o registro de amamentação e mamadeiras com sono e fraldas, depois consulte os relatórios. Esses recursos do aplicativo são separados das ferramentas gratuitas do site.',
    sections: [
      ['Comece pelo perfil correto', 'Entre na conta e configure a jornada do bebê com a data de nascimento. Confira o perfil selecionado antes de registrar um cuidado. As ações disponíveis variam entre as fases de bebê e criança.', 'Preencha os detalhes úteis, confira horário e perfil e salve. Use os controles de edição para corrigir uma entrada.'],
      ['Amamentação: registrar uma mamada', 'Escolha amamentação e o peito inicial. Use o cronômetro durante a mamada ou o registro manual quando ela já terminou. Confira início e fim na entrada manual; pare o cronômetro ao terminar.', 'O registro informa tempo e lado. A duração não mede quanto leite foi transferido nem determina se a mamada foi suficiente.'],
      ['Mamadeira: leite, quantidade e unidade', 'Escolha mamadeira, informe o horário e selecione leite materno ou fórmula. Escolha mL ou oz, anote a quantidade e salve. Confira a unidade ao consultar registros ou mudar de aparelho.', 'O registro lembra as quantidades informadas. Não recomenda uma meta de consumo nem orienta o preparo de fórmula: siga as instruções do produto e do profissional de saúde.'],
      ['Sono: guardar um período de descanso', 'Escolha sono e use os controles de início e fim disponíveis. Encerre um cronômetro ativo quando o bebê acordar. Consulte entradas concluídas para ver sonecas e sono noturno.', 'O registro depende das suas anotações. Não detecta sono automaticamente, prevê a próxima soneca ou avalia a segurança do ambiente de dormir.'],
      ['Fraldas: registrar a troca', 'Escolha a entrada de fralda, selecione o tipo e salve o horário. Essas notas ficam no mesmo perfil das mamadas e mamadeiras.', 'Consulte os registros para lembrar do dia ou preparar uma consulta. A contagem de fraldas, sozinha, não confirma hidratação nem descarta doença.'],
      ['Ler relatórios e exportar dados', 'As visualizações Dia, Semana, Lista e Resumo organizam os dados do bebê selecionado. O download CSV guarda uma cópia dos registros disponíveis; confira perfil e intervalo de datas antes de exportar.', 'Um período vazio pode significar falta de registros. Os totais descrevem entradas salvas, sem diagnóstico, avaliação de crescimento ou comprovação de que uma rotina funciona.', 'Análises com IA e alguns recursos avançados têm acesso específico: {premium}'],
      ['Calculadoras, listas e crescimento no site', 'Em {tools}, use estimativas de ovulação e parto, calendário de consultas e sintomas, listas de preparação, nomes favoritos e registro de crescimento, sem conta no aplicativo.', 'Adicione tarefas e notas, filtre a lista, marque itens concluídos ou desnecessários, imprima ou baixe uma cópia. O registro de crescimento traça suas medidas e oferece referências da OMS de peso por idade nas idades disponíveis; não calcula um percentil individual.', 'Os dados salvos ficam neste aparelho e não sincronizam automaticamente com o aplicativo. Limpar os dados do navegador pode apagá-los: baixe as cópias que deseja conservar.', 'Para os dados da conta e sua retenção: {privacy}']
    ],
    takeaways: ['Confira o perfil antes de registrar alimentação, sono ou fraldas.', 'Mamadas registram tempo e lado; mamadeiras registram leite, quantidade e unidade.', 'Os relatórios têm Dia, Semana, Lista, Resumo e download CSV.', 'Falta de registros significa dados ausentes.', 'Site e aplicativo mantêm registros separados: guarde cópias.'],
    faq: [['Posso acompanhar alimentação e fraldas juntas?', 'Sim. Registre mamadas, mamadeiras e trocas com seus horários no perfil do bebê, depois consulte os relatórios.'], ['E se eu amamentar e também der mamadeira?', 'Use amamentação para o peito e mamadeira para leite ordenhado ou fórmula. Minutos de mamada e volume de mamadeira não são medidas equivalentes de ingestão.'], ['O registro prevê a próxima soneca?', 'Ele guarda períodos de sono e mostra os registros. Não promete previsão de soneca nem um plano personalizado.'], ['O registro de crescimento do site aparece no aplicativo?', 'Não. Os dados do site ficam no aparelho. Use as cópias de segurança e digite separadamente no aplicativo o que desejar.'], ['Todos os recursos são gratuitos?', 'O acesso varia por conta e plataforma. A Jornada Diária e as ferramentas públicas não exigem Premium ativo; confira os recursos avançados e de IA no aplicativo.']]
  },
  premium: {
    title: 'BeMama grátis e Premium: acesso aos recursos',
    description: 'Entenda a Jornada Diária gratuita, as ferramentas do site e o acesso aos recursos Premium da BeMama antes de escolher uma assinatura.',
    intro: 'Escolha os recursos pela tarefa: ler a jornada, registrar cuidados, preparar uma lista ou consultar uma explicação com IA. O aplicativo mostra o acesso da sua conta e plataforma; nem todos os recursos são necessariamente gratuitos.',
    sections: [
      ['Jornada Diária sem Premium ativo', 'No aplicativo atual, a Jornada Diária continua disponível após o fim de um teste ou assinatura. Você pode continuar lendo os conteúdos da sua fase, incluindo gravidez, sem comprar Premium.', 'Para configurar: {daily}'],
      ['Ferramentas públicas sem conta', 'As calculadoras, listas e outras ferramentas de {tools} são gratuitas e não exigem login ou compra de Premium.', 'Seus registros ficam separados da conta do aplicativo. Quando a ferramenta oferecer backup, baixe uma cópia para conservar fora do navegador.'],
      ['Recursos com acesso adicional', 'Ferramentas avançadas, algumas funções da comunidade e a IA têm controles próprios de acesso. Exemplos incluem certas ferramentas de crescimento com dados salvos e análises de relatórios por IA, conforme os recursos disponíveis na conta.', 'Abra a função desejada e leia a tela de acesso ou assinatura. Confira recursos, preço, renovação e limites do teste. Premium não promete atendimento prioritário, consulta clínica ou resultado específico.'],
      ['Antes de assinar ou alterar uma assinatura', 'Leia {terms} e os detalhes da loja ou tela de compra. Gerencie a assinatura na plataforma em que você a contratou.', 'Para problemas de acesso ou conta: {contact}. Não envie dados completos de cartão de pagamento.']
    ],
    takeaways: ['A Jornada Diária não exige Premium ativo.', 'As ferramentas públicas são gratuitas e não pedem conta.', 'Ferramentas avançadas e IA podem exigir acesso adicional.', 'Confira recursos e cobrança na tela de compra atual.', 'Os dados do site e da conta do aplicativo ficam separados.'],
    faq: [['A Jornada Diária acaba quando termina o teste?', 'No aplicativo atual, ela continua disponível sem Premium ativo. O acesso a outros recursos pode mudar.'], ['Preciso de Premium para as calculadoras do site?', 'Não. As calculadoras e listas públicas funcionam sem conta ou assinatura Premium.'], ['Onde vejo o preço e os recursos incluídos?', 'Nas telas de recursos e assinatura da sua conta e plataforma. Consulte também os termos antes da compra.'], ['Premium inclui atendimento médico?', 'Não. As ferramentas e explicações com IA ajudam na organização e informação geral, sem diagnóstico, tratamento ou atendimento de emergência.']]
  },
  'getting-started': {
    title: 'Comece na BeMama: gravidez e cuidados do bebê',
    description: 'Configure sua jornada e o perfil do bebê na BeMama, salve o primeiro registro ou experimente ferramentas gratuitas no site sem conta.',
    intro: 'Comece com uma tarefa útil: acompanhar sua semana de gravidez, anotar uma mamadeira ou preparar a mala da maternidade. O aplicativo e as ferramentas web têm formas diferentes de configuração e salvamento.',
    sections: [
      ['1. Escolha o aplicativo ou uma ferramenta web', 'Para a Jornada Diária e os registros do bebê, abra {app} ou baixe BeMama pelos links Android e iOS. Escolha o idioma e crie uma conta ou entre na sua conta existente.', 'Para uma calculadora ou lista sem conta, abra {tools} e leia as instruções antes de inserir informações.'],
      ['2. Configure a jornada certa', 'Escolha planejamento, gravidez, bebê ou criança e preencha os dados solicitados. Confira os campos: a última menstruação e o nascimento do bebê são datas com funções diferentes.', 'Atualize a jornada quando a fase mudar. Antes de registrar cuidados, confira o perfil para que os dados fiquem na criança correta.', 'Para acompanhamento da gravidez: {daily}'],
      ['3. Registre um evento e confira', 'No perfil do bebê, escolha amamentação, mamadeira, sono ou fralda. Informe horário e detalhes, revise e salve. Pare o cronômetro quando o evento acabar.', 'Abra os relatórios e confira bebê e dia. Edite os erros em vez de criar entradas duplicadas.', 'Veja o passo a passo de cada registro: {tracking}'],
      ['4. Salve cópias do trabalho no site', 'Em uma lista, marque tarefas concluídas ou desnecessárias, adicione tarefas e notas próprias e filtre a visualização. O progresso considera as tarefas que contam para a conclusão.', 'Use as opções de salvamento e backup oferecidas. Baixe ou imprima uma cópia. Os dados ficam neste aparelho, sem sincronização automática com o aplicativo; limpar os dados do navegador pode removê-los.'],
      ['5. Confira acesso e escolhas sobre os dados', 'A Jornada Diária e as ferramentas públicas não exigem Premium ativo. Veja outros requisitos em {premium}.', 'Antes de guardar dados sensíveis, leia {privacy}. Solicite uma exportação enquanto a conta estiver ativa se precisar de uma cópia. Para ajuda: {contact}.']
    ],
    takeaways: ['Use uma conta para a Jornada Diária e os registros do bebê.', 'Experimente as ferramentas públicas sem conta.', 'Confira fase, perfil, data e unidades antes de salvar.', 'Revise a primeira entrada nos relatórios e corrija erros.', 'Guarde backups e diferencie os registros web dos registros do aplicativo.'],
    faq: [['Posso usar BeMama pela web?', 'Sim: {app}. Os guias e ferramentas públicas estão no {website}. O login no aplicativo e o salvamento no site são separados.'], ['O que registrar primeiro?', 'Um evento útil de lembrar, como uma mamada, mamadeira ou período de sono. Confira perfil e horário, salve e consulte o relatório.'], ['Por que meu relatório está vazio?', 'Confira bebê, intervalo de datas e se a entrada foi salva. Um relatório vazio não significa ausência de cuidados. Fale com o suporte se registros esperados não aparecerem.'], ['Preciso registrar tudo?', 'Não. Escolha o que ajuda e siga eventuais orientações de acompanhamento da sua equipe de saúde. O aplicativo organiza informações; não é uma obrigação para cuidar bem.']]
  }
});
