export const routinesFr = {
  sleep: {
    title: 'Sommeil de bébé à 4 mois : un rythme souple',
    description: 'Organisez le sommeil de bébé à quatre mois avec une frise explicative, des totaux de sommeil, les limites du carnet et des sources fiables.',
    intro: 'Un rythme de sommeil utile part des journées récentes de bébé, de ses besoins alimentaires et de ses signes de fatigue. Un exemple horaire aide à lire un carnet, sans fixer la prochaine sieste. Explorez la frise, puis préparez vos questions pour votre équipe de soins.',
    sections: [
      ['Que comprend le total quotidien ?', 'L’AASM recommande 12 à 16 heures de sommeil par 24 heures, siestes comprises, pour les bébés de 4 à 12 mois. Ce repère collectif ne fixe ni heure du coucher ni nombre de siestes pour chaque bébé. {sleepSource}', 'Additionnez les périodes réellement notées comme du sommeil, en distinguant les réveils et les périodes non renseignées. Le temps entre le coucher et le lever n’est pas nécessairement du temps dormi.'],
      ['Relire la veille avant de préparer la journée', 'Choisissez une période constante, par exemple de 07:00 à 07:00 le lendemain. Vérifiez le profil, le début et la fin des entrées et le passage de minuit. Corrigez un minuteur resté en marche avant d’utiliser le total.', 'Une courte sieste suit-elle une sortie ? Une longue nuit vient-elle d’un minuteur oublié ? Un trou signifie-t-il qu’une sieste manque ? Ces questions aident davantage qu’une note de réussite de la journée.'],
      ['Explorer un exemple de carnet de sommeil', 'Cette journée fictive contient trois siestes et trois périodes de sommeil nocturne, séparées par des réveils. Elle illustre le calcul d’un total. Ces horaires et ce nombre de siestes ne sont pas des recommandations. Les repas et autres soins ne sont pas dessinés et ne doivent pas attendre pour respecter la frise.', 'Passez à l’après-midi incomplet : le total baisse lorsqu’une partie de la journée n’est pas renseignée. Cela ne prouve pas que bébé a moins dormi. La période manquante reste inconnue.'],
      ['Adapter le rythme quand la journée change', 'Après une sieste plus courte, notez ce qui s’est passé et réévaluez la suite selon les signes de bébé. Inutile de maintenir un bébé épuisé éveillé pour atteindre une heure d’exemple. Un réveil plus tardif n’oblige pas à précipiter les activités suivantes.', 'Gardez une préparation au sommeil simple et répétable. Une journée différente ne suffit pas à conclure à une régression ou à choisir un apprentissage du sommeil. Parlez d’une difficulté persistante en tenant compte des repas, de la santé et de la vie familiale.'],
      ['Distinguer horaires et sécurité du couchage', 'Couchez bébé sur le dos, sur une surface ferme et plane, avec un drap-housse et sans objets mous ni literie libre. Consultez l’AAP pour le couchage séparé adapté et les changements comme le retournement. {safeSleep}', 'Une frise ne vérifie pas la sécurité du lit. Si bébé est né prématurément ou suivi pour une maladie, demandez comment interpréter son âge et les conseils. Pour des repères en français sur l’évolution du sommeil : {local}.'],
      ['Noter l’essentiel et préparer une question', 'Dans BeMama, choisissez le profil, notez début et fin du sommeil, puis consultez les rapports. L’application ne détecte pas automatiquement le sommeil et ne prédit pas la prochaine sieste. {tracking}', 'Apportez quelques journées représentatives et une question précise : « Voici ce que nous avons noté ; quels éléments faut-il prendre en compte ? » Notez séparément repas et changements utiles. En cas de maladie apparente ou de souci d’alimentation ou de respiration, demandez un avis médical plutôt que de modifier les horaires.']
    ],
    takeaways: ['Additionnez siestes et sommeil nocturne dans une période définie.', 'Le repère AASM concerne les 4–12 mois, sans imposer un emploi du temps.', 'Une période non renseignée est inconnue, pas forcément éveillée.', 'Ne retardez pas un repas nécessaire pour suivre cet exemple.', 'Le carnet aide à observer ; il ne prédit ni ne diagnostique.'],
    faq: [['Une courte sieste signifie-t-elle que le rythme est mauvais ?', 'Une entrée isolée n’explique pas la journée. Vérifiez le carnet et les besoins de bébé. Demandez conseil pour une difficulté persistante.'], ['Faut-il retarder une tétée pour préserver la sieste ?', 'N’utilisez pas cette illustration pour retarder un repas. Suivez les signes de faim et le plan individuel de votre équipe de soins.'], ['La frise indique-t-elle le besoin de sommeil de mon bébé ?', 'Non. Elle montre un carnet fictif et son calcul. Le repère par âge est distinct et la situation de votre bébé doit être prise en compte.'], ['Peut-on comparer les totaux si des entrées manquent ?', 'Seulement en signalant cette limite. Un total inférieur peut refléter des notes absentes, sans baisse mesurée du sommeil.']],
    evidence: { guidance: ['Le repère AASM garde son âge d’application. La frise BeMama est un exemple original, pas un horaire clinique validé. La source Naître et grandir apporte un contexte en français.'], bemama: 'BeMama conserve les événements saisis. Les rapports ne reconstituent pas les périodes de sommeil non notées.', safety: 'Les repas et les soins passent avant l’exemple horaire. Un professionnel qualifié peut examiner une difficulté propre à votre bébé.' }
  },
  feeding: {
    title: 'Alimentation de bébé à 6 mois : lait et diversification',
    description: 'Préparez la diversification à six mois avec le lait, les signes de préparation et une fiche imprimable pour noter repas et observations.',
    intro: 'Vers six mois, la diversification alimentaire fait une place aux premiers aliments tout en poursuivant les apports de lait. Les capacités de bébé, ses signes de faim et les conseils individuels comptent plus qu’une heure fixe. Utilisez l’exemple et la fiche pour organiser vos observations.',
    sections: [
      ['Partir des capacités de bébé et de ses repas habituels', 'Le NHS et les CDC situent l’introduction des aliments complémentaires vers six mois, avec les signes de préparation. L’âge seul ne suffit pas. En cas de prématurité ou de plan alimentaire particulier, demandez conseil. {feedingSource} {readiness}', 'Selon le NHS, le lait maternel ou la préparation pour nourrissons reste la boisson principale pendant la première année. L’exemple ne remplace pas une prise de lait. Les recommandations locales peuvent différer : la ressource québécoise explique aussi les aliments complémentaires. {local}'],
      ['Préparer une occasion de découvrir un aliment', 'Les CDC décrivent notamment le contrôle de la tête et du cou, la position assise avec soutien et la capacité à avaler. Installez bébé droit, bien soutenu, et restez avec lui pendant qu’il mange. Adaptez texture et préparation à ses capacités. {readiness}', 'Choisissez un moment calme où vous pouvez être disponible. Cette page n’impose pas lait ou aliments en premier : suivez les conseils locaux et le plan de votre bébé.'],
      ['Une journée avec des occasions souples', 'Les lignes décrivent des moments, pas un nombre obligatoire de repas. Les prises de lait répondent aux besoins pendant la journée et, si nécessaire, la nuit. Déplacez l’occasion de goûter si bébé est fatigué ou peu intéressé.', 'L’exemple ne fixe ni quantité ni objectif de consommation, et n’exige pas les mêmes aliments, le même lait ou le même ordre pour toutes les familles.'],
      ['Garder une fiche d’observation des repas', 'Notez l’heure, le sein ou le biberon et l’aliment ou la texture proposés. Pour un biberon, gardez la quantité avec son unité. Pour une tétée, durée ou côté peuvent être utiles ; les minutes au sein ne se convertissent pas en volume de lait.', 'Ajoutez les signes observés, comme se détourner ou montrer de l’intérêt, et vos questions. Une quantité non renseignée est inconnue, pas nulle. La fiche ne donne pas de score nutritionnel.'],
      ['Si bébé refuse ou si la journée change', 'Si bébé se détourne ou ferme la bouche, faites une pause et répondez à ses signes plutôt que de forcer le programme. Notez sans juger la journée. Demandez conseil pour des refus persistants, un doute sur les apports ou des signes de maladie.', 'Cette page ne fournit ni protocole d’introduction des allergènes ni gestes d’urgence contre l’étouffement. Consultez des conseils locaux fiables sur la préparation, les allergies et la sécurité, surtout en présence d’un risque individuel. {readiness}'],
      ['Utiliser BeMama pour se souvenir des événements', 'Vérifiez le profil. Choisissez l’allaitement pour une tétée et le biberon pour le lait exprimé ou la préparation infantile, avec l’unité mL ou oz choisie. Notez les aliments séparément et consultez le bon jour dans les rapports. {tracking}', 'Une entrée manquante peut expliquer un trou. L’application ne mesure pas le lait reçu au sein et ne décide pas des besoins de bébé. Pour une vue d’ensemble des premiers aliments : {solids}.']
    ],
    takeaways: ['Vers six mois, tenez compte des capacités et des conseils individuels.', 'Les premiers aliments accompagnent le lait.', 'Les moments proposés sont souples, sans quantité ou nombre imposé.', 'Durée de tétée et volume du biberon sont différents.', 'Notez les signes et questions ; consultez pour les difficultés.'],
    faq: [['Les aliments remplacent-ils le lait à six mois ?', 'N’utilisez pas cet exemple pour remplacer le lait. Les premiers aliments accompagnent les prises de lait selon les besoins et les conseils propres à votre bébé.'], ['Faut-il garder les mêmes horaires ?', 'Non. Adaptez les occasions et suivez les signes de bébé. L’exemple ne fixe ni heures ni nombre de repas.'], ['Quelle quantité en mL ou oz faut-il écrire ?', 'La quantité observée au biberon et son unité, si vous souhaitez la noter. La fiche ne calcule aucun objectif et ne convertit pas les minutes de tétée en volume.'], ['BeMama peut-elle dire si bébé a assez mangé ?', 'L’application organise les notes. Elle ne juge pas la suffisance des apports et ne diagnostique pas les difficultés : parlez-en à votre équipe de soins.']],
    evidence: { guidance: ['Les sources NHS et CDC donnent les repères de départ ; Naître et grandir apporte le contexte québécois. Les détails nationaux peuvent différer. La fiche reste un outil d’organisation.'], bemama: 'Durée de tétée, volume au biberon et aliments sont des données distinctes. Les rapports ne mesurent pas l’adéquation nutritionnelle.', safety: 'Demandez un avis individuel en cas de prématurité, allergie connue ou difficulté alimentaire. Une routine ne doit pas retarder des soins.' }
  }
};
