export const routinesEs = {
  sleep: {
    title: 'Sueño del bebé de 4 meses: una rutina flexible',
    description: 'Organiza el sueño a los cuatro meses con una línea de tiempo, totales explicados, límites de los registros y fuentes sobre sueño seguro.',
    intro: 'Una rutina útil parte de los días recientes del bebé, sus necesidades de alimentación y señales de cansancio. Un ejemplo horario ayuda a leer un registro; no prescribe la próxima siesta. Explora el gráfico y prepara tus preguntas para el equipo de salud.',
    sections: [
      ['Qué incluye el total diario de sueño', 'La AASM recomienda de 12 a 16 horas por cada 24 horas, incluidas las siestas, para bebés de 4 a 12 meses. Esta orientación por edad no fija una hora de acostarse o número de siestas individual. {sleepSource}', 'Suma períodos de sueño completados, distinguiendo despertares registrados y espacios desconocidos. El intervalo entre acostarse y levantarse no equivale necesariamente a tiempo dormido.'],
      ['Revisa ayer antes de organizar hoy', 'Elige un período constante, como 07:00 a 07:00 del día siguiente. Revisa perfil, inicio, final y entradas que cruzan medianoche. Corrige un temporizador olvidado antes de usar el total.', '¿La siesta corta coincidió con una salida? ¿Una noche muy larga es un temporizador sin detener? ¿Falta una entrada? Son preguntas más útiles que calificar el día como bueno o malo.'],
      ['Explora un registro de ejemplo', 'El día ficticio tiene tres siestas y tres períodos nocturnos con despertares entre ellos. Enseña a sumar registros, sin recomendar esos horarios ni ese número de siestas. Las tomas y otros cuidados no están dibujados y no deben retrasarse para encajar.', 'Selecciona la tarde incompleta: el total baja cuando no se registra parte del día. Eso no demuestra que el bebé durmiera menos. El período sin datos es desconocido, no vigilia confirmada.'],
      ['Adapta la rutina cuando cambia el día', 'Tras una siesta más corta, registra lo ocurrido y revisa la siguiente actividad según las señales del bebé. No mantengas despierto a un bebé agotado para alcanzar una hora del ejemplo. Un despertar tardío tampoco obliga a acelerar todo lo demás.', 'Mantén una preparación sencilla y repetible para dormir. Un día distinto no basta para diagnosticar una regresión o decidir entrenamiento del sueño. Comenta preocupaciones persistentes junto con alimentación, salud y contexto familiar.'],
      ['Separa horario y seguridad al dormir', 'Coloca al bebé boca arriba, sobre una superficie firme y plana, con sábana ajustable y sin objetos blandos ni ropa de cama suelta. Consulta la guía AAP para el espacio separado y cambios como darse la vuelta. {safeSleep}', 'El gráfico no evalúa la seguridad del entorno. Si el bebé nació prematuro o tiene una condición médica, consulta cómo interpretar su edad y las recomendaciones. Contexto sobre el sueño en español: {local}.'],
      ['Registra lo útil y prepara una pregunta', 'En BeMama, selecciona el perfil, registra inicio y fin del sueño y consulta los informes. La app no detecta automáticamente el sueño ni promete la próxima siesta. {tracking}', 'Lleva varios días representativos y una pregunta: «Esto es lo registrado; ¿qué contexto debemos considerar?». Anota por separado tomas y cambios relevantes. Si parece enfermo o te preocupa su alimentación o respiración, busca consejo médico en vez de ajustar el horario.']
    ],
    takeaways: ['Suma siestas y sueño nocturno en un período definido.', 'El rango AASM corresponde a los 4–12 meses, no a un horario individual.', 'Un período sin registros es desconocido.', 'No retrases una toma necesaria por el ejemplo.', 'El registro ayuda a observar; no predice ni diagnostica.'],
    faq: [['¿Una siesta corta significa que la rutina está mal?', 'Una entrada aislada no explica el día. Comprueba que el registro esté completo y considera las señales del bebé. Consulta si la preocupación persiste.'], ['¿Debo retrasar una toma para conservar la siesta?', 'No uses esta ilustración para retrasar la alimentación. Sigue las señales del bebé y cualquier plan individual de su equipo de salud.'], ['¿El gráfico muestra cuánto necesita dormir mi bebé?', 'No. Muestra un registro ficticio y sus sumas. La orientación por edad es independiente y la situación del bebé necesita contexto.'], ['¿Puedo comparar días con registros incompletos?', 'Solo indicando esa limitación. Un total menor puede deberse a entradas ausentes y no demuestra menos sueño.']],
    evidence: { guidance: ['El rango AASM conserva su grupo de edad. El ejemplo BeMama es original y no es un horario clínico. HealthyChildren ofrece contexto adicional en español.'], bemama: 'BeMama guarda los eventos introducidos. Los informes no reconstruyen el sueño que no se registró.', safety: 'Las necesidades de alimentación y cuidado van antes que el ejemplo. Consulta a un profesional por preocupaciones sobre tu bebé.' }
  },
  feeding: {
    title: 'Alimentación a los 6 meses: leche y primeros alimentos',
    description: 'Organiza la alimentación complementaria a los seis meses con leche, señales de preparación y una hoja imprimible para registrar observaciones.',
    intro: 'Alrededor de los seis meses, la alimentación complementaria introduce alimentos mientras continúan las tomas de leche. La preparación, las señales del bebé y las indicaciones individuales importan más que el reloj. Usa el ejemplo y la hoja para organizar observaciones.',
    sections: [
      ['Parte de la preparación y las tomas habituales', 'El NHS y los CDC describen el inicio de alimentos complementarios alrededor de los seis meses, con preparación del desarrollo. La edad sola no decide. Consulta por prematuridad o un plan alimentario individual. {feedingSource} {readiness}', 'Según el NHS, la leche materna o fórmula infantil sigue siendo la bebida principal durante el primer año. El ejemplo no reemplaza una toma de leche. Para el contexto de la Asociación Española de Pediatría: {local}.'],
      ['Prepara una oportunidad de probar alimentos', 'Los CDC incluyen entre las señales el control de cabeza y cuello, sentarse con apoyo y tragar en vez de expulsar la comida. Usa un asiento erguido y con apoyo, acompaña al bebé y adapta textura y preparación a sus capacidades. {readiness}', 'Elige un momento tranquilo con tiempo para observar. Esta página no impone leche o sólidos primero: sigue la orientación local y el plan del bebé.'],
      ['Un día con oportunidades flexibles', 'Las filas son momentos del día, no un número obligatorio de tomas o comidas. Las tomas de leche siguen las necesidades, incluso de noche cuando corresponda. Puedes mover la oportunidad de probar alimentos si está cansado o sin interés.', 'El ejemplo no asigna cantidades ni metas de ingesta. Tampoco exige los mismos alimentos, leche u orden para todas las familias.'],
      ['Guarda una hoja de observaciones', 'Anota la hora, si fue pecho o biberón, y alimentos o texturas ofrecidos. En el biberón, conserva cantidad y unidad original. En lactancia, registra duración o lado si te sirve; los minutos al pecho no se convierten en volumen de leche.', 'Añade señales observadas, como girar la cabeza o mostrar interés, y preguntas. Un campo vacío es desconocido, no cero. La hoja no da una puntuación nutricional.'],
      ['Si rechaza alimentos o cambia el día', 'Si gira la cabeza o cierra la boca, pausa y responde a sus señales en lugar de forzar el plan. Anota sin juzgar el día. Consulta por rechazo persistente, dudas sobre ingesta o signos de enfermedad.', 'Esta guía no establece un protocolo de alérgenos ni enseña atención urgente de atragantamientos. Consulta fuentes locales fiables sobre preparación, alergias y seguridad, especialmente con riesgos individuales. {readiness}'],
      ['Usa BeMama para recordar eventos', 'Comprueba el perfil. Usa lactancia para el pecho y biberón para leche extraída o fórmula, guardando la unidad mL u oz elegida. Registra alimentos por separado y consulta el día correcto en informes. {tracking}', 'Una entrada ausente puede explicar un hueco. La app no calcula la leche transferida al pecho ni decide las necesidades del bebé. Introducción general a los alimentos: {solids}.']
    ],
    takeaways: ['Alrededor de seis meses, considera preparación e indicaciones individuales.', 'Los primeros alimentos acompañan la leche.', 'Los momentos son flexibles, sin cantidades ni número obligatorio.', 'Duración al pecho y volumen del biberón son diferentes.', 'Registra señales y preguntas; consulta las dificultades.'],
    faq: [['¿Los sólidos reemplazan la leche a los seis meses?', 'No uses este ejemplo para reemplazar leche. Los primeros alimentos acompañan las tomas según las necesidades e indicaciones de tu bebé.'], ['¿Todos los días deben tener los mismos horarios?', 'No. Adapta las oportunidades y responde a las señales. El ejemplo no fija horas ni número de tomas.'], ['¿Cuántos mL u oz debo escribir?', 'La cantidad observada en el biberón con su unidad, si quieres registrarla. La hoja no calcula metas ni convierte minutos de lactancia en volumen.'], ['¿BeMama dice si ha comido suficiente?', 'Organiza lo registrado; no evalúa suficiencia ni diagnostica problemas de alimentación. Lleva las preocupaciones al equipo de salud.']],
    evidence: { guidance: ['NHS y CDC aportan los criterios generales; la AEP ofrece recomendaciones en español. Los detalles locales pueden variar. La hoja es un organizador, no un plan clínico.'], bemama: 'Tiempo de lactancia, volumen de biberón y sólidos son registros separados. Los informes no miden suficiencia nutricional.', safety: 'Busca consejo individual por prematuridad, alergia conocida o dificultades al comer. No uses una rutina para retrasar atención.' }
  }
};
