export const routinesPt = {
  sleep: {
    title: 'Sono do bebê de 4 meses: uma rotina flexível',
    description: 'Organize o sono aos quatro meses com uma linha do tempo, totais explicados, limites dos registros e fontes sobre um ambiente seguro.',
    intro: 'Uma rotina útil começa pelos dias recentes do bebê, pelas necessidades de alimentação e pelos sinais de cansaço. Um exemplo de horários ajuda a ler um registro, mas não determina a próxima soneca. Explore o gráfico e prepare suas perguntas para a equipe de saúde.',
    sections: [
      ['O que entra no total de sono?', 'A AASM recomenda 12 a 16 horas por 24 horas, incluindo sonecas, para bebês de 4 a 12 meses. Essa orientação por idade não define horário de dormir nem número individual de sonecas. {sleepSource}', 'Some períodos de sono concluídos, separando despertares registrados e intervalos desconhecidos. O tempo entre deitar e levantar não corresponde necessariamente ao tempo dormido.'],
      ['Reveja ontem antes de organizar hoje', 'Escolha um intervalo constante, como 07:00 até 07:00 do dia seguinte. Confira perfil, início, fim e registros que atravessam a meia-noite. Corrija um cronômetro esquecido antes de usar o total.', 'A soneca curta coincidiu com um passeio? Uma noite longa é um cronômetro sem encerrar? Falta alguma anotação? Essas perguntas ajudam mais do que dar uma nota ao dia.'],
      ['Explore um registro de exemplo', 'O dia fictício tem três sonecas e três períodos noturnos, com despertares entre eles. Ele ensina a somar registros; os horários e o número de sonecas não são recomendações. Mamadas e outros cuidados não estão desenhados e não devem esperar para caber no gráfico.', 'Escolha a tarde incompleta: o total cai quando parte do dia não foi registrada. Isso não prova que o bebê dormiu menos. O intervalo ausente permanece desconhecido.'],
      ['Adapte o ritmo quando o dia mudar', 'Depois de uma soneca mais curta, registre o ocorrido e reavalie a próxima atividade pelos sinais do bebê. Não mantenha um bebê exausto acordado para alcançar o horário do exemplo. Um despertar tardio também não exige apressar o restante.', 'Mantenha uma preparação simples e repetível para dormir. Um dia diferente não basta para concluir que há regressão ou escolher treinamento de sono. Converse sobre preocupações persistentes considerando alimentação, saúde e contexto familiar.'],
      ['Separe horário e segurança ao dormir', 'Coloque o bebê de barriga para cima, em superfície firme e plana, com lençol ajustado e sem objetos macios ou roupa de cama solta. Consulte a AAP sobre o espaço separado e mudanças como rolar. {safeSleep}', 'O gráfico não avalia o berço. Em caso de prematuridade ou condição médica, pergunte como interpretar idade e recomendações. Veja também as orientações da Sociedade Brasileira de Pediatria: {local}.'],
      ['Registre o necessário e prepare uma pergunta', 'Na BeMama, escolha o perfil, registre início e fim do sono e confira os relatórios. O aplicativo não detecta sono automaticamente nem prevê a próxima soneca. {tracking}', 'Leve alguns dias representativos e uma pergunta: “Isso foi o que registramos; que contexto devemos considerar?”. Anote mamadas e mudanças relevantes separadamente. Se o bebê parecer doente ou houver preocupação com alimentação ou respiração, procure orientação médica em vez de ajustar horários.']
    ],
    takeaways: ['Some sonecas e sono noturno em um intervalo definido.', 'A faixa AASM é para 4–12 meses, não um horário individual.', 'Um intervalo sem registro é desconhecido.', 'Não atrase uma mamada necessária para seguir o exemplo.', 'O registro ajuda a observar; não prevê nem diagnostica.'],
    faq: [['Uma soneca curta significa que a rotina está errada?', 'Uma entrada isolada não explica o dia. Confira os registros e os sinais do bebê. Procure orientação se a preocupação persistir.'], ['Devo adiar uma mamada para preservar a soneca?', 'Não use esta ilustração para atrasar alimentação. Siga os sinais do bebê e qualquer plano individual da equipe de saúde.'], ['O gráfico mostra quanto meu bebê precisa dormir?', 'Não. Mostra um registro fictício e sua soma. A orientação por idade é separada, e seu bebê precisa ser considerado individualmente.'], ['Posso comparar dias com registros incompletos?', 'Somente indicando essa limitação. Um total menor pode vir de anotações ausentes, sem redução medida do sono.']],
    evidence: { guidance: ['A faixa AASM mantém seu grupo etário. O exemplo BeMama é original e não é um horário clínico. A SBP complementa as informações de segurança em português.'], bemama: 'BeMama guarda os eventos inseridos. Os relatórios não reconstroem sono que não foi anotado.', safety: 'Alimentação e cuidados vêm antes dos horários do exemplo. Consulte um profissional sobre preocupações específicas com seu bebê.' }
  },
  feeding: {
    title: 'Alimentação do bebê de 6 meses: leite e primeiros alimentos',
    description: 'Organize a introdução alimentar aos seis meses com leite, sinais de prontidão e uma ficha para imprimir e registrar suas observações.',
    intro: 'Por volta dos seis meses, a introdução alimentar abre espaço para alimentos enquanto as mamadas continuam. Prontidão, sinais do bebê e orientações individuais importam mais que o relógio. Use o exemplo e a ficha para organizar observações.',
    sections: [
      ['Comece pela prontidão e mamadas habituais', 'NHS e CDC descrevem o início de alimentos complementares por volta dos seis meses, com prontidão do desenvolvimento. A idade sozinha não decide. Consulte a equipe em caso de prematuridade ou plano alimentar individual. {feedingSource} {readiness}', 'Segundo o NHS, leite materno ou fórmula infantil continua sendo a bebida principal no primeiro ano. O exemplo não substitui uma mamada. Para orientações brasileiras de alimentação infantil: {local}.'],
      ['Prepare uma oportunidade de conhecer alimentos', 'O CDC inclui controle de cabeça e pescoço, sentar com apoio e engolir em vez de empurrar a comida para fora. Use assento ereto e com apoio, acompanhe a refeição e adapte textura e preparo às capacidades do bebê. {readiness}', 'Escolha um momento tranquilo com tempo para observar. Esta página não impõe leite ou sólidos primeiro: siga as orientações locais e o plano individual.'],
      ['Um dia com oportunidades flexíveis', 'As linhas são momentos do dia, não uma quantidade obrigatória de mamadas ou refeições. O leite responde às necessidades durante o dia e, quando necessário, à noite. Mude a oportunidade de explorar alimentos se houver cansaço ou falta de interesse.', 'Não há quantidades ou metas de consumo. O exemplo também não exige os mesmos alimentos, leite ou ordem para todas as famílias.'],
      ['Guarde uma ficha de observações', 'Anote horário, peito ou mamadeira, alimento e textura oferecidos. Na mamadeira, mantenha a quantidade com a unidade original. Na amamentação, anote duração ou lado se for útil; minutos no peito não se convertem em volume de leite.', 'Inclua sinais observados, como virar o rosto ou mostrar interesse, e suas perguntas. Um campo vazio é desconhecido, não zero. A ficha não dá uma pontuação nutricional.'],
      ['Se houver recusa ou um dia diferente', 'Se o bebê virar o rosto ou fechar a boca, faça uma pausa e responda aos sinais em vez de forçar o plano. Registre sem julgar o dia. Converse com um profissional sobre recusa persistente, dúvidas sobre ingestão ou sinais de doença.', 'Este guia não estabelece protocolo de alérgenos nem ensina atendimento de emergência para engasgo. Consulte fontes locais confiáveis sobre preparo, alergias e segurança, especialmente com riscos individuais. {readiness}'],
      ['Use BeMama para lembrar eventos', 'Confira o perfil. Use amamentação para o peito e mamadeira para leite ordenhado ou fórmula, guardando a unidade mL ou oz escolhida. Registre sólidos separadamente e veja o dia correto nos relatórios. {tracking}', 'Uma entrada ausente pode explicar uma lacuna. O aplicativo não calcula o leite transferido no peito nem define as necessidades do bebê. Visão geral dos primeiros alimentos: {solids}.']
    ],
    takeaways: ['Por volta de seis meses, considere prontidão e orientação individual.', 'Primeiros alimentos acompanham o leite.', 'Os momentos são flexíveis, sem quantidade ou número obrigatório.', 'Duração no peito e volume de mamadeira são diferentes.', 'Registre sinais e perguntas; consulte dificuldades.'],
    faq: [['Sólidos substituem o leite aos seis meses?', 'Não use o exemplo para substituir leite. Os primeiros alimentos acompanham mamadas conforme necessidades e orientação individual.'], ['Precisa ter os mesmos horários todos os dias?', 'Não. Adapte as oportunidades e responda aos sinais. O exemplo não fixa horários nem número de mamadas.'], ['Quantos mL ou oz devo escrever?', 'A quantidade observada na mamadeira e sua unidade, se quiser registrá-la. A ficha não calcula metas nem converte tempo de amamentação em volume.'], ['BeMama diz se meu bebê comeu o suficiente?', 'Organiza registros; não avalia suficiência nem diagnostica problemas alimentares. Leve suas preocupações à equipe de saúde.']],
    evidence: { guidance: ['NHS e CDC fornecem os critérios gerais; o Ministério da Saúde traz o contexto brasileiro. Detalhes locais podem variar. A ficha organiza observações, sem criar um plano clínico.'], bemama: 'Tempo de amamentação, volume da mamadeira e sólidos são registros separados. Relatórios não medem adequação nutricional.', safety: 'Busque orientação individual para prematuridade, alergia conhecida ou dificuldade alimentar. Não use a rotina para adiar cuidados.' }
  }
};
