export const routinesTr = {
  sleep: {
    title: '4 aylık bebek uyku düzeni: esnek bir gün',
    description: 'Dört aylık bebeğin uyku düzenini örnek zaman çizelgesi, açıklamalı uyku toplamları, eksik kayıt karşılaştırması ve güvenilir kaynaklarla inceleyin.',
    intro: 'Yararlı bir uyku düzeni bebeğinizin son günlerinden, beslenme ihtiyacından ve yorgunluk işaretlerinden başlar. Saatli bir örnek kaydı okumaya yardımcı olur; sonraki uykuyu belirlemez. Çizelgeyi inceleyip sağlık ekibinize soracağınız soruları hazırlayın.',
    sections: [
      ['Günlük uyku toplamına neler dahil?', 'AASM, 4–12 aylık bebekler için gündüz uykuları dahil 24 saatte 12–16 saat uyku önerir. Bu yaş grubu bilgisi her bebeğe özel yatış saati veya uyku sayısı belirlemez. {sleepSource}', 'Tamamlanmış uyku dönemlerini toplayın; kayıtlı uyanıklığı ve bilinmeyen aralıkları ayırın. Yatağa girmek ile sabah kalkmak arasındaki süre, uyunan süre olmayabilir.'],
      ['Bugünü planlamadan dünü inceleyin', '07:00’den ertesi gün 07:00’ye kadar gibi sabit bir aralık seçin. Profili, başlangıç ve bitişleri, gece yarısını aşan kayıtları kontrol edin. Açık unutulan zamanlayıcıyı toplamı kullanmadan düzeltin.', 'Kısa uyku bir gezintiye mi denk geldi? Uzun gece, durdurulmayan zamanlayıcı mı? Eksik bir kayıt var mı? Bunlar günü iyi veya kötü diye puanlamaktan daha yararlı sorulardır.'],
      ['Örnek uyku kaydını keşfedin', 'Bu kurgusal günde üç gündüz ve üç gece uyku kaydı, aralarında uyanıklık vardır. Örnek yalnızca toplamayı öğretir; saatler ve uyku sayısı öneri değildir. Beslenme ve diğer bakım çizilmemiştir; çizelgeye uydurmak için geciktirilmemelidir.', 'Eksik öğleden sonrayı seçin: günün bir bölümü kaydedilmeyince toplam azalır. Bu, bebeğin daha az uyuduğunu kanıtlamaz. Kayıtsız aralık bilinmeyendir; doğrulanmış uyanıklık değildir.'],
      ['Gün değiştiğinde düzeni uyarlayın', 'Kısa bir uykudan sonra olanı kaydedip sonraki bölümü bebeğin işaretlerine göre değerlendirin. Örnek saate ulaşmak için çok yorgun bebeği uyanık tutmayın. Geç başlayan bir sabah da kalan işleri aceleye getirmenizi gerektirmez.', 'Basit ve tekrarlanabilir bir uyku hazırlığı seçin. Farklı bir gün tek başına uyku gerilemesi ya da uyku eğitimi kararı anlamına gelmez. Süren kaygıları beslenme, sağlık ve aile koşullarıyla birlikte konuşun.'],
      ['Saatleri güvenli uyku ortamından ayırın', 'Bebeği sırtüstü, sert ve düz bir yüzeye, gergin çarşafla; yumuşak nesne ve gevşek örtü olmadan yatırın. Ayrı uyku alanı ve dönme gibi değişiklikler için AAP rehberine bakın. {safeSleep}', 'Çizelge yatağın güvenliğini değerlendirmez. Prematüre doğum veya tıbbi durum varsa yaş ve uyku önerilerini nasıl yorumlayacağınızı sorun. Türkçe dört aylık gelişim ve uyku bağlamı: {local}.'],
      ['Gerekeni kaydedip bir soru hazırlayın', 'BeMama’da profili seçin, uyku başlangıç ve bitişini kaydedip raporlara bakın. Uygulama uykuyu otomatik algılamaz ve sonraki uykuyu vaat etmez. {tracking}', 'Birkaç temsil edici gün ve bir soru götürün: “Bunları kaydettik; hangi koşulları dikkate almalıyız?”. Beslenme ve önemli değişiklikleri ayrıca not edin. Hastalık görünümü, beslenme veya solunum kaygısında saatleri değiştirmek yerine tıbbi yardım alın.']
    ],
    takeaways: ['Gündüz ve gece uykularını belirli bir aralıkta toplayın.', 'AASM aralığı 4–12 ay içindir; bireysel çizelge değildir.', 'Kayıtsız dönem bilinmeyendir.', 'Gereken beslenmeyi örneğe uydurmak için geciktirmeyin.', 'Kayıt gözleme yardımcıdır; tahmin veya tanı değildir.'],
    faq: [['Kısa uyku düzenin yanlış olduğunu mu gösterir?', 'Tek kayıt bütün günü açıklamaz. Kayıtların tamamlığını ve bebeğin işaretlerini kontrol edin. Kaygı sürerse danışın.'], ['Uykuyu korumak için beslenmeyi ertelemeli miyim?', 'Bu örneği beslenmeyi geciktirmek için kullanmayın. Bebeğin işaretlerine ve sağlık ekibinin bireysel planına uyun.'], ['Çizelge bebeğimin uyku ihtiyacını gösterir mi?', 'Hayır. Kurgusal bir kaydı ve toplamayı gösterir. Yaş grubu önerisi ayrıdır; bebeğinizin koşulları değerlendirilmelidir.'], ['Eksik kayıtlarla günleri karşılaştırabilir miyim?', 'Yalnızca sınırlılığı belirterek. Düşük toplam eksik girişlerden kaynaklanabilir; daha az uyku ölçüldüğünü göstermez.']],
    evidence: { guidance: ['AASM aralığının yaş kapsamı korunur. BeMama örneği özgündür ve klinik çizelge değildir. Türkçe kaynak yaş ve uyku konusunun yerel anlatımını sağlar; onun kesin saat hedefleri kullanılmaz.'], bemama: 'BeMama girdiğiniz olayları saklar. Raporlar kaydedilmemiş uykuyu yeniden oluşturmaz.', safety: 'Beslenme ve bakım ihtiyaçları örnek saatlerden önce gelir. Bebeğinize özgü kaygıları yetkin bir sağlık uzmanıyla görüşün.' }
  },
  feeding: {
    title: '6 aylık bebek beslenmesi: süt ve ek gıda düzeni',
    description: 'Altı aylık bebek için süt, ek gıdaya hazır olma işaretleri ve esnek öğün fırsatlarını inceleyin; yazdırılabilir gözlem formunu kullanın.',
    intro: 'Altı ay civarında ek gıdalar tanıtılırken sütle beslenme sürer. Hazır olma, bebeğin işaretleri ve bireysel öneriler saatten önemlidir. Gün örneğini ve formu gözlemleri düzenlemek için kullanın.',
    sections: [
      ['Hazır olma ve alışılmış süt öğünleriyle başlayın', 'NHS ve CDC, gelişimsel hazır olmayı dikkate alarak ek gıdalara yaklaşık altı ayda başlanmasını açıklar. Yaş tek başına karar değildir. Prematüre doğum veya bireysel beslenme planında ekibinize danışın. {feedingSource} {readiness}', 'NHS’ye göre anne sütü veya bebek formülü ilk yıl temel içecek olmayı sürdürür. Örnek bir süt öğününün yerine geçmez. Türkiye’de 6–8 aylık beslenme hakkında: {local}.'],
      ['Bir ek gıda fırsatını hazırlayın', 'CDC’nin işaretleri arasında baş ve boyun kontrolü, destekle oturma ve yiyeceği dışarı itmek yerine yutma vardır. Dik ve destekli oturuş sağlayın, yerken yanında kalın ve dokuyu becerilerine uyarlayın. {readiness}', 'Gözlem için zamanınızın olduğu sakin bir an seçin. Bu sayfa önce süt veya önce katı gıda kuralı koymaz; yerel öneri ve bireysel plana uyun.'],
      ['Esnek beslenme fırsatları olan bir gün', 'Satırlar günün bölümleridir; zorunlu öğün sayısı değildir. Sütle beslenme gündüz ve gerektiğinde gece ihtiyaçlara yanıt verir. Bebek yorgun veya ilgisizse yiyecek deneme fırsatını başka zamana alın.', 'Miktar veya tüketim hedefi verilmez. Her ailenin aynı yiyeceği, sütü ya da sırayı kullanması gerekmez.'],
      ['Beslenme gözlem formu tutun', 'Saati, meme veya biberonu, sunulan yiyecek ve dokuyu yazın. Biberonda miktarı özgün birimiyle saklayın. Emzirmede süre veya taraf yararlıysa yazılabilir; memedeki dakikalar süt hacmine çevrilemez.', 'Başını çevirme veya ilgi gösterme gibi gözlemleri ve sorularınızı ekleyin. Boş miktar bilinmeyendir, sıfır değildir. Form beslenme puanı vermez.'],
      ['Yiyecek reddi veya farklı bir gün olduğunda', 'Bebek başını çevirir veya ağzını kapatırsa plana zorlamak yerine durup işaretlerine yanıt verin. Günü yargılamadan not edin. Süren ret, alım kaygısı veya hastalık belirtilerini uzmanla görüşün.', 'Bu rehber alerjen tanıtım protokolü veya boğulmaya acil müdahale eğitimi değildir. Hazırlama, alerji ve güvenlik için güvenilir yerel kaynaklara, bireysel risklerde uzman önerisine başvurun. {readiness}'],
      ['BeMama’yı olayları hatırlamak için kullanın', 'Profili kontrol edin. Memede beslenme için emzirme, sağılmış süt veya mama için biberonu seçin; mL veya oz birimini miktarla saklayın. Ek gıdayı ayrı kaydedip doğru günün raporuna bakın. {tracking}', 'Eksik giriş bir boşluğu açıklayabilir. Uygulama emzirmede alınan sütü hesaplamaz veya bebeğin ihtiyacını belirlemez. Ek gıdaya genel bakış: {solids}.']
    ],
    takeaways: ['Yaklaşık altı ayda hazır olma ve bireysel öneriyi dikkate alın.', 'İlk gıdalar sütle beslenmeye eşlik eder.', 'Gün bölümleri esnektir; zorunlu miktar veya sayı yoktur.', 'Emzirme süresi ve biberon hacmi farklıdır.', 'İşaret ve soruları yazın; güçlükleri uzmana danışın.'],
    faq: [['Ek gıdalar altı ayda sütün yerine geçer mi?', 'Bu örneği sütün yerine kullanmayın. İlk yiyecekler bebeğin ihtiyaçları ve bireysel öneri doğrultusunda sütle beslenmeye eşlik eder.'], ['Her gün aynı saatler gerekir mi?', 'Hayır. Fırsatları uyarlayın ve bebeğin işaretlerine yanıt verin. Örnek sabit saat veya öğün sayısı belirlemez.'], ['Kaç mL veya oz yazmalıyım?', 'Kaydetmek istiyorsanız gözlemlediğiniz biberon miktarını birimiyle yazın. Form hedef hesaplamaz ve emzirme dakikasını hacme çevirmez.'], ['BeMama yeterince yediğini söyler mi?', 'Kayıtları düzenler; yeterliliği değerlendirmez veya beslenme sorunlarına tanı koymaz. Kaygıları sağlık ekibinizle görüşün.']],
    evidence: { guidance: ['NHS ve CDC genel çerçeveyi; Sağlık Bakanlığı kaynağı Türkçe bağlamı sağlar. Yerel ayrıntılar değişebilir. Form, klinik plan değil gözlem düzenleyicisidir.'], bemama: 'Emzirme süresi, biberon hacmi ve ek gıdalar ayrı kayıtlardır. Raporlar beslenme yeterliliğini ölçmez.', safety: 'Prematüre doğum, bilinen alerji veya beslenme güçlüğünde bireysel öneri alın. Rutini bakımı geciktirmek için kullanmayın.' }
  }
};
