// Stable task IDs preserve earlier checked items. Additional tasks are original
// organizational prompts informed by the linked NHS guidance, not a care plan.
const langs=['en','fa','ar','fr','tr','es','pt'];
const t=(row,lang)=>{const parts=row.split('|');if(parts.length!==7)throw Error(row);return parts[Math.max(0,langs.indexOf(lang))];};
const groups={
  care:'Care and appointments|مراقبت و ویزیت‌ها|الرعاية والمواعيد|Soins et rendez-vous|Bakım ve randevular|Atención y citas|Cuidados e consultas',
  everyday:'Everyday preparation|آمادگی روزمره|التحضير اليومي|Préparation quotidienne|Günlük hazırlık|Preparación diaria|Preparação diária',
  support:'People and practical plans|همراهان و برنامه‌های عملی|الأشخاص والخطط العملية|Entourage et organisation|Destek ve pratik planlar|Apoyo y organización|Apoio e organização',
  documents:'Documents and travel|مدارک و رفت‌وآمد|الوثائق والتنقل|Documents et trajet|Belgeler ve ulaşım|Documentos y traslado|Documentos e transporte',
  parent:'For you|برای شما|لكِ|Pour vous|Sizin için|Para ti|Para você',
  baby:'For your baby|برای نوزاد|لطفلكِ|Pour bébé|Bebeğiniz için|Para tu bebé|Para seu bebê',
  companion:'For your companion|برای همراه|لمرافقك|Pour votre accompagnant|Refakatçiniz için|Para tu acompañante|Para seu acompanhante',
  sleep:'Sleep space|محل خواب|مكان النوم|Espace de sommeil|Uyku alanı|Espacio para dormir|Espaço para dormir',
  feeding:'Feeding preparation|آمادگی تغذیه|الاستعداد للتغذية|Préparer les repas|Beslenme hazırlığı|Preparación de alimentación|Preparação para alimentação',
  changing:'Clothing and changing|پوشاک و تعویض پوشک|الملابس وتغيير الحفاض|Vêtements et change|Giyim ve alt değiştirme|Ropa y cambio de pañal|Roupas e troca de fraldas',
};
// Existing indices stay mapped to their original task, irrespective of grouping.
const baseGroups={
 'preconception-checklist':['care','care','care','care','everyday','care'],
 'hospital-bag-checklist':['documents','parent','parent','baby','baby','parent'],
 'registry-checklist':['sleep','documents','changing','feeding','care','changing'],
 'newborn-care-checklist':['feeding','care','sleep','care','care','support']
};
const extras={
 'preconception-checklist':[
 ['medicine-list','care','List prescriptions, supplements and doses for your visit|فهرست داروها، مکمل‌ها و دوزها برای ویزیت|اكتبي الأدوية والمكملات وجرعاتها للزيارة|Lister médicaments, compléments et doses pour la visite|Randevu için ilaç, takviye ve dozları listeleyin|Anota medicamentos, suplementos y dosis para la cita|Liste medicamentos, suplementos e doses para a consulta'],
 ['family-history','care','Write down personal and family health questions|پرسش‌های سلامت شخصی و خانوادگی را بنویسید|دوّني أسئلة الصحة الشخصية والعائلية|Noter les questions de santé personnelle et familiale|Kişisel ve aile sağlığı sorularını yazın|Anota preguntas sobre salud personal y familiar|Anote dúvidas de saúde pessoal e familiar'],
 ['screening','care','Ask which screening checks apply to you|دربارهٔ غربالگری مناسب خود بپرسید|اسألي عن الفحوص المناسبة لك|Demander quels dépistages vous concernent|Size uygun taramaları sorun|Pregunta qué revisiones te corresponden|Pergunte quais exames se aplicam a você'],
 ['folate','care','Confirm your folic-acid and supplement plan with a professional|برنامهٔ اسیدفولیک و مکمل‌ها را با متخصص بررسی کنید|راجعي خطة حمض الفوليك والمكملات مع مختص|Confirmer le programme de folates et compléments avec un professionnel|Folik asit ve takviye planını uzmanla doğrulayın|Confirma con un profesional tu plan de ácido fólico y suplementos|Confirme com um profissional o plano de ácido fólico e suplementos'],
 ['smoke','everyday','Arrange help to stop smoking if needed|در صورت نیاز برای ترک سیگار کمک بگیرید|رتّبي دعماً للإقلاع عن التدخين عند الحاجة|Prévoir une aide au sevrage tabagique si nécessaire|Gerekirse sigarayı bırakma desteği ayarlayın|Organiza apoyo para dejar de fumar si lo necesitas|Organize apoio para parar de fumar se necessário'],
 ['alcohol','everyday','Plan alcohol-free routines while trying to conceive|برنامهٔ بدون الکل هنگام اقدام به بارداری|خططي لروتين بلا كحول أثناء محاولة الحمل|Prévoir des habitudes sans alcool pendant les essais|Gebelik planlarken alkolsüz rutin oluşturun|Planifica rutinas sin alcohol mientras buscas embarazo|Planeje rotinas sem álcool ao tentar engravidar'],
 ['food','everyday','Plan manageable meals and regular movement|وعده‌های مناسب و تحرک منظم را برنامه‌ریزی کنید|خططي لوجبات عملية وحركة منتظمة|Prévoir des repas pratiques et une activité régulière|Uygulanabilir öğünler ve düzenli hareket planlayın|Organiza comidas prácticas y movimiento regular|Planeje refeições práticas e movimento regular'],
 ['partner','support','Discuss shared responsibilities with your support person|مسئولیت‌ها را با فرد حامی در میان بگذارید|ناقشي المسؤوليات المشتركة مع الداعم لك|Discuter du partage des responsabilités|Destek kişinizle sorumlulukları konuşun|Habla del reparto de responsabilidades con tu apoyo|Converse sobre responsabilidades com sua rede de apoio'],
 ['contact','support','Save your clinic contact and questions for follow-up|تماس درمانگاه و پرسش‌های پیگیری را ذخیره کنید|احفظي اتصال العيادة وأسئلة المتابعة|Enregistrer les coordonnées du cabinet et questions de suivi|Klinik iletişimini ve takip sorularını kaydedin|Guarda el contacto de la clínica y preguntas de seguimiento|Salve o contato da clínica e dúvidas para acompanhamento'],
 ['meds-safety','care','Discuss treatment changes before changing any prescribed medicine|پیش از تغییر داروی تجویزی با پزشک صحبت کنید|ناقشي أي تغيير قبل تعديل دواء موصوف|Discuter avant toute modification d’un traitement prescrit|Reçeteli ilaçları değiştirmeden önce görüşün|Consulta antes de cambiar cualquier medicamento recetado|Converse antes de alterar qualquer medicamento prescrito']
 ],
 'hospital-bag-checklist':[
 ['birth-notes','documents','Birth preferences and maternity records|ترجیحات زایمان و پروندهٔ بارداری|تفضيلات الولادة وسجل الحمل|Souhaits de naissance et dossier de maternité|Doğum tercihleri ve gebelik kayıtları|Preferencias de parto e historial del embarazo|Preferências de parto e registros da gestação'],
 ['transport','documents','Confirm the route, transport and contact number|مسیر، وسیلهٔ رفت‌وآمد و شماره تماس را مشخص کنید|أكدي الطريق ووسيلة النقل ورقم الاتصال|Confirmer trajet, transport et numéro de contact|Güzergâh, ulaşım ve iletişim numarasını doğrulayın|Confirma ruta, transporte y teléfono de contacto|Confirme trajeto, transporte e telefone'],
 ['hospital-supplies','documents','Check what your hospital provides before buying supplies|پیش از خرید، وسایل ارائه‌شدهٔ بیمارستان را بررسی کنید|تحققي مما يوفره المستشفى قبل الشراء|Vérifier ce que fournit la maternité avant d’acheter|Alışverişten önce hastanenin sağladıklarını öğrenin|Comprueba qué proporciona tu hospital antes de comprar|Veja o que a maternidade fornece antes de comprar'],
 ['medicines','parent','Regular medicines and medication list|داروهای معمول و فهرست آن‌ها|الأدوية المعتادة وقائمتها|Traitements habituels et liste des médicaments|Düzenli ilaçlar ve ilaç listesi|Medicamentos habituales y su lista|Medicamentos habituais e lista'],
 ['toiletries','parent','Toothbrush, toiletries and hair ties|مسواک، لوازم بهداشتی و کش مو|فرشاة أسنان وأدوات نظافة وربطات شعر|Brosse à dents, toilette et attaches-cheveux|Diş fırçası, bakım ürünleri ve saç tokası|Cepillo de dientes, aseo y gomas de pelo|Escova de dentes, higiene e elásticos'],
 ['pads','parent','Maternity pads and comfortable underwear|نوار بهداشتی پس از زایمان و لباس زیر راحت|فوط نفاس وملابس داخلية مريحة|Protections maternité et sous-vêtements confortables|Lohusa pedi ve rahat iç çamaşırı|Compresas posparto y ropa interior cómoda|Absorventes pós-parto e roupa íntima confortável'],
 ['footwear','parent','Slippers and shower footwear|دمپایی و پاپوش حمام|نعال وحذاء للاستحمام|Chaussons et sandales de douche|Terlik ve duş terliği|Zapatillas y calzado de ducha|Chinelos e calçado para banho'],
 ['nightwear','parent','Nightwear and a spare change of clothes|لباس خواب و یک دست لباس اضافه|ملابس نوم وملابس إضافية|Vêtements de nuit et tenue de rechange|Gecelik ve yedek kıyafet|Pijama y muda de ropa|Pijama e troca de roupa'],
 ['glasses','parent','Glasses or other personal essentials|عینک یا وسایل ضروری شخصی|النظارات أو الضروريات الشخصية|Lunettes et essentiels personnels|Gözlük veya kişisel ihtiyaçlar|Gafas u otros objetos personales|Óculos e outros itens pessoais'],
 ['nappies','baby','Newborn diapers and changing supplies|پوشک نوزاد و وسایل تعویض|حفاضات مولود ومستلزمات التغيير|Couches nouveau-né et nécessaire de change|Yenidoğan bezi ve değiştirme malzemeleri|Pañales de recién nacido y material de cambio|Fraldas de recém-nascido e itens de troca'],
 ['spare-baby','baby','Spare baby bodysuits and sleepsuits|بادی و سرهمی اضافهٔ نوزاد|ملابس داخلية ونوم إضافية للطفل|Bodies et pyjamas de rechange|Yedek bebek zıbını ve tulumu|Bodys y pijamas de recambio|Bodies e macacões extras'],
 ['weather','baby','Weather-appropriate clothes for the journey home|لباس مناسب هوا برای بازگشت به خانه|ملابس تناسب الطقس للعودة|Tenue adaptée à la météo pour le retour|Eve dönüş için havaya uygun kıyafet|Ropa adecuada al clima para volver a casa|Roupa adequada ao clima para a volta'],
 ['seat','baby','Arrange a suitable car seat if travelling by car|در صورت سفر با خودرو، صندلی مناسب کودک آماده کنید|جهزي مقعد سيارة مناسباً عند السفر بالسيارة|Prévoir un siège-auto adapté pour le trajet en voiture|Arabayla gidecekseniz uygun oto koltuğu hazırlayın|Prepara una silla adecuada si viajas en coche|Providencie cadeirinha adequada se for de carro'],
 ['partner-clothes','companion','Companion’s spare clothing and toiletries|لباس اضافه و لوازم بهداشتی همراه|ملابس إضافية وأدوات نظافة للمرافق|Rechange et toilette de l’accompagnant|Refakatçinin yedek kıyafet ve bakım ürünleri|Ropa y aseo de tu acompañante|Roupa e higiene do acompanhante'],
 ['partner-phone','companion','Companion’s phone, charger and contact list|تلفن، شارژر و فهرست تماس همراه|هاتف المرافق وشاحنه وقائمة الاتصال|Téléphone, chargeur et contacts de l’accompagnant|Refakatçinin telefonu, şarjı ve iletişim listesi|Teléfono, cargador y contactos del acompañante|Telefone, carregador e contatos do acompanhante'],
 ['partner-food','companion','Companion’s food and drinks|خوراکی و نوشیدنی همراه|طعام وشراب للمرافق|Repas et boissons de l’accompagnant|Refakatçi için yiyecek ve içecek|Comida y bebida del acompañante|Comida e bebida do acompanhante'],
 ['washing','parent','Bag for used clothes|کیسهٔ لباس‌های استفاده‌شده|كيس للملابس المستعملة|Sac à linge utilisé|Kirli kıyafet torbası|Bolsa para ropa usada|Saco para roupa usada'],
 ['feeding-check','baby','Confirm feeding supplies with the maternity team|وسایل تغذیه را با تیم زایمان بررسی کنید|راجعي مستلزمات التغذية مع فريق الولادة|Confirmer le matériel d’alimentation avec la maternité|Beslenme malzemelerini doğum ekibiyle doğrulayın|Confirma el material de alimentación con maternidad|Confirme os itens de alimentação com a maternidade']
 ],
 'registry-checklist':[
 ['mattress','sleep','Check the mattress is firm, flat and fits the cot|سفت، صاف و اندازه بودن تشک تخت را بررسی کنید|تأكدي أن المرتبة صلبة ومستوية وتناسب السرير|Vérifier un matelas ferme, plat et bien ajusté|Yatağın sert, düz ve beşiğe uygun olduğunu kontrol edin|Comprueba que el colchón sea firme, plano y ajustado|Confira se o colchão é firme, plano e ajustado'],
 ['sheets','sleep','Fitted sheets and spare bedding appropriate for safe sleep|ملحفهٔ کش‌دار و رختخواب اضافهٔ مناسب خواب ایمن|ملاءات محكمة وأغطية احتياطية مناسبة للنوم الآمن|Draps-housses et rechange adaptés au sommeil sûr|Güvenli uykuya uygun lastikli çarşaf ve yedekleri|Sábanas ajustables y recambio para sueño seguro|Lençóis ajustados e extras para sono seguro'],
 ['no-extras','sleep','Review safe-sleep guidance before buying pillows or cot accessories|پیش از خرید بالش یا لوازم تخت، راهنمای خواب ایمن را بخوانید|راجعي النوم الآمن قبل شراء وسائد أو إكسسوارات السرير|Lire les conseils de sommeil sûr avant les accessoires de lit|Yastık veya beşik aksesuarı almadan güvenli uyku önerilerini okuyun|Revisa el sueño seguro antes de comprar almohadas o accesorios|Leia orientações de sono seguro antes de comprar travesseiros ou acessórios'],
 ['mat','changing','Wipe-clean changing mat|زیرانداز قابل تمیزکردن تعویض|حصيرة تغيير سهلة التنظيف|Matelas à langer lavable|Silinebilir alt değiştirme matı|Cambiador fácil de limpiar|Trocador fácil de limpar'],
 ['towels','changing','Washcloths and soft towels|دستمال شست‌وشو و حولهٔ نرم|قطع غسل ومناشف ناعمة|Gants de toilette et serviettes douces|Yıkama bezleri ve yumuşak havlular|Paños y toallas suaves|Panos e toalhas macias'],
 ['weather-clothes','changing','Clothes for your season and home temperature|پوشاک مناسب فصل و دمای خانه|ملابس تناسب الفصل وحرارة المنزل|Vêtements adaptés à la saison et au logement|Mevsim ve ev sıcaklığına uygun kıyafet|Ropa para la estación y temperatura de casa|Roupas para a estação e temperatura de casa'],
 ['bottles','feeding','If using bottles: bottles, teats and cleaning supplies|در صورت استفاده از شیشه: شیشه، سرشیشه و وسایل شست‌وشو|عند استخدام الرضّاعات: رضّاعات وحلمات وأدوات تنظيف|Si biberons : biberons, tétines et matériel de nettoyage|Biberon kullanılıyorsa: biberon, uç ve temizleme malzemeleri|Si usas biberones: biberones, tetinas y limpieza|Se usar mamadeiras: mamadeiras, bicos e limpeza'],
 ['feeding-support','feeding','Save a feeding-support contact before purchasing extras|پیش از خرید وسایل اضافه، تماس پشتیبان تغذیه را ذخیره کنید|احفظي جهة دعم التغذية قبل شراء الإضافات|Enregistrer un contact d’aide à l’alimentation avant les achats supplémentaires|Ek ürün almadan beslenme desteği iletişimini kaydedin|Guarda un contacto de apoyo antes de comprar extras de alimentación|Salve um contato de apoio antes de comprar extras de alimentação'],
 ['travel-bag','documents','Bag for supplies when leaving home|کیف وسایل بیرون از خانه|حقيبة للمستلزمات خارج المنزل|Sac pour les sorties|Dışarı çıkarken malzeme çantası|Bolsa para salir de casa|Bolsa para sair de casa'],
 ['seat-fit','documents','Read the car seat installation instructions|راهنمای نصب صندلی خودرو را بخوانید|اقرئي تعليمات تركيب مقعد السيارة|Lire la notice d’installation du siège-auto|Oto koltuğu kurulum talimatını okuyun|Lee las instrucciones de instalación de la silla|Leia as instruções de instalação da cadeirinha'],
 ['budget','support','Set a budget and list what you already own or can borrow|بودجه و وسایل موجود یا قابل قرض را بنویسید|حددي ميزانية وما لديك أو يمكنك استعارته|Fixer un budget et lister les articles disponibles ou empruntables|Bütçe belirleyin, mevcut veya ödünç alınabilecekleri listeleyin|Fija presupuesto y anota lo que tienes o puedes pedir prestado|Defina orçamento e liste o que tem ou pode pegar emprestado'],
 ['shared-list','support','Add quantities and who is arranging each item in Notes|تعداد و مسئول تهیه را در یادداشت هر مورد بنویسید|أضيفي الكمية ومن سيجهز العنصر في الملاحظات|Noter les quantités et la personne responsable|Miktar ve temin edecek kişiyi Notlar’a yazın|Añade cantidades y quién consigue cada cosa en Notas|Adicione quantidades e responsáveis em Notas']
 ],
 'newborn-care-checklist':[
 ['followup','care','Confirm the first check-up date and where to go|تاریخ و محل نخستین معاینه را مشخص کنید|أكدي تاريخ ومكان أول فحص|Confirmer date et lieu du premier examen|İlk kontrolün tarih ve yerini doğrulayın|Confirma fecha y lugar de la primera revisión|Confirme data e local da primeira consulta'],
 ['numbers','care','Save routine and urgent care contact numbers|شمارهٔ مراقبت معمول و فوری را ذخیره کنید|احفظي أرقام الرعاية العادية والعاجلة|Enregistrer les contacts de soins et d’urgence|Rutin ve acil bakım numaralarını kaydedin|Guarda teléfonos de atención habitual y urgente|Salve contatos de atendimento e urgência'],
 ['questions','care','Write questions to bring to the baby’s first visit|پرسش‌های نخستین ویزیت نوزاد را بنویسید|اكتبي أسئلة لأول زيارة للطفل|Préparer les questions du premier rendez-vous|Bebeğin ilk randevusu için soruları yazın|Anota preguntas para la primera visita del bebé|Anote dúvidas para a primeira consulta do bebê'],
 ['feeding-contact','feeding','Know who to call for feeding difficulties|بدانید برای مشکل تغذیه با چه کسی تماس بگیرید|اعرفي بمن تتصلين عند صعوبة التغذية|Identifier qui appeler en cas de difficulté d’alimentation|Beslenme zorluğunda kimi arayacağınızı bilin|Identifica a quién llamar si hay dificultades de alimentación|Saiba a quem recorrer se houver dificuldade na alimentação'],
 ['bottle-cleaning','feeding','If using bottles, review safe preparation and cleaning|در صورت استفاده از شیشه، آماده‌سازی و شست‌وشوی ایمن را مرور کنید|عند استخدام الرضّاعات راجعي التحضير والتنظيف الآمن|Si biberons, revoir préparation et nettoyage sûrs|Biberon varsa güvenli hazırlama ve temizlemeyi gözden geçirin|Si usas biberones, revisa preparación y limpieza seguras|Se usar mamadeiras, reveja preparo e limpeza seguros'],
 ['sleep-carers','sleep','Share safe-sleep instructions with every caregiver|راهنمای خواب ایمن را با همهٔ مراقبان در میان بگذارید|شاركي تعليمات النوم الآمن مع جميع مقدمي الرعاية|Partager les consignes de sommeil sûr avec tous les aidants|Güvenli uyku bilgisini tüm bakıcılarla paylaşın|Comparte las pautas de sueño seguro con cada cuidador|Compartilhe orientações de sono seguro com todos os cuidadores'],
 ['changing-ready','changing','Put changing supplies within reach before starting|پیش از شروع، وسایل تعویض را در دسترس قرار دهید|ضعي أدوات التغيير في المتناول قبل البدء|Préparer le nécessaire de change à portée de main|Başlamadan değiştirme malzemelerini elinizin altına alın|Prepara el material de cambio al alcance antes de empezar|Deixe os itens de troca ao alcance antes de começar'],
 ['visitors','support','Agree visiting plans and ask unwell visitors to postpone|برنامهٔ دیدارها را مشخص و از مهمان بیمار بخواهید به تعویق بیندازد|اتفقي على الزيارات واطلبي من المرضى تأجيلها|Organiser les visites et demander aux personnes malades de reporter|Ziyaretleri planlayın ve hasta ziyaretçilerden ertelemelerini isteyin|Acuerda visitas y pide aplazarlas a quien esté enfermo|Combine visitas e peça que pessoas doentes adiem'],
 ['meals-help','support','Arrange help with meals, errands or older children|برای غذا، خرید یا کودکان بزرگ‌تر کمک هماهنگ کنید|رتّبي مساعدة للوجبات والمشاوير والأطفال الأكبر|Organiser l’aide aux repas, courses ou aînés|Yemek, alışveriş veya büyük çocuklar için yardım ayarlayın|Organiza ayuda con comidas, recados o hijos mayores|Organize ajuda com refeições, tarefas ou filhos maiores'],
 ['handover','support','Write a simple handover note for your support person|یادداشت تحویل مراقبت برای فرد حامی بنویسید|اكتبي ملاحظة تسليم رعاية للداعم|Préparer une note de relais pour votre entourage|Destek kişisine bakım devir notu yazın|Escribe una nota para quien releve el cuidado|Escreva uma nota para quem assumir os cuidados']
 ]
};
const sourceUrls={
 'preconception-checklist':'https://www.nhs.uk/pregnancy/trying-for-a-baby/trying-to-get-pregnant/',
 'hospital-bag-checklist':'https://www.nhs.uk/best-start-in-life/pregnancy/preparing-for-labour-and-birth/hospital-bag-checklist/',
 'registry-checklist':'https://www.nhs.uk/best-start-in-life/pregnancy/preparing-for-labour-and-birth/what-to-buy-for-your-newborn-baby/',
 'newborn-care-checklist':'https://www.nhs.uk/best-start-in-life/baby/baby-basics/caring-for-your-baby/'
};
export function checklistContent(id,lang,legacyItems) {
 if(!baseGroups[id])return undefined;
 const tasks=[...legacyItems.map((title,index)=>({id:`base-${index}`,title,group:baseGroups[id][index]})),...extras[id].map(([key,group,title])=>({id:key,group,title:t(title,lang)}))];
 const categoryIds=[...new Set(tasks.map(task=>task.group))];
 return {tasks,groups:categoryIds.map(id=>({id,title:t(groups[id],lang)})),sources:[{label:'NHS',url:sourceUrls[id]}]};
}
